require "system.fluidflow"
require "system.saveload"
require "system.road"

local csystem = require "register.csystem"

csystem "roadnet"
csystem "station"
csystem "generator"
csystem "powergrid"
csystem "fluid"
csystem "assembling"
csystem "chimney"
csystem "laboratory"
csystem "hub"
csystem "task"
