require "system.fluidflow"
require "system.saveload"

local csystem = require "register.csystem"

csystem "endpoint"
csystem "roadnet"
csystem "generator"
csystem "powergrid"
csystem "fluid"
csystem "assembling"
csystem "chimney"
csystem "laboratory"
--csystem "trading"
csystem "hub"
csystem "task"
