local world = ...
local convert = assert(loadfile "/convert_road.lua")()

local road = {
    {
        prototype_name = "砖石公路-U型",
        dir = "N",
        x = 116,
        y = 139,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 138,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 137,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 136,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 135,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 134,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 133,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 132,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 131,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 130,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 129,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 128,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 127,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 116,
        y = 126,
    },
    {
        prototype_name = "砖石公路-L型",
        dir = "E",
        x = 116,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 117,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 118,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 119,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 120,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 121,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 122,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 123,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 124,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 125,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 126,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 127,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 128,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 129,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 130,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 131,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 132,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 133,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 134,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 135,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 136,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 137,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 138,
        y = 125,
    },
    {
        prototype_name = "砖石公路-T型",
        dir = "S",
        x = 139,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 140,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 141,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 142,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 143,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 144,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 145,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 146,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 147,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 148,
        y = 125,
    },
    {
        prototype_name = "砖石公路-U型",
        dir = "W",
        x = 149,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 124,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 123,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 122,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 121,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 120,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 119,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 118,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 117,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 116,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 115,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 114,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 113,
    },
    {
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 139,
        y = 112,
    },
    {
        prototype_name = "砖石公路-U型",
        dir = "S",
        x = 139,
        y = 111,
    },
}
world:roadnet_load_map(convert(road))


world:create_entity "指挥中心"{
	prototype_name = "指挥中心",
	dir = "S",
	x = 126,
	y = 126,
}

world:create_entity "采矿机I"{
	dir = "E",
	prototype_name = "采矿机I",
	recipe = "铁矿石挖掘",
	x = 140,
	y = 112,
}

world:create_entity "物流中心I"{
	dir = "N",
	prototype_name = "物流中心I",
	x = 125,
	y = 122
}
