local entities = {
    {
        prototype_name = "指挥中心",
        dir = "N",
        items = {
	        {"铁板",200},
	        {"石砖",200},
	        {"采矿机I",4},
	        {"铸造厂I",1},
	        {"铸造厂I",1},
	        {"水电站I",1},
	        {"蒸馏厂I",2},
	        {"化工厂I",2},
	        {"破损水电站",2},
	        {"破损空气过滤器",3},
	        {"破损电解厂",1},
	        {"破损化工厂",6},
	        {"破损组装机",3},
	        {"破损铁制电线杆",10},
	        {"破损物流中心",4},
	        {"破损运输车辆",8},
	        {"破损车站",4},
        },
        x = 126,
        y = 126,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 160,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 159,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 158,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 157,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 156,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 155,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 154,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 153,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 152,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 151,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 150,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 149,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 148,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "E",
        x = 147,
        y = 132,
    },
	{
        prototype_name = "砖石公路-L型",
        dir = "E",
        x = 146,
        y = 132,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 146,
        y = 133,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 146,
        y = 134,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 146,
        y = 135,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "N",
        x = 146,
        y = 136,
    },
	{
        prototype_name = "砖石公路-L型",
        dir = "W",
        x = 146,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 145,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 144,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 143,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 142,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 141,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 140,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 139,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 138,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 137,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 136,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 135,
        y = 137,
    },
	{
        prototype_name = "砖石公路-I型",
        dir = "W",
        x = 134,
        y = 137,
    },
	{
        prototype_name = "物流中心",
        dir = "S",
        x = 134,
        y = 138,
    },
}

return {
    entities = entities,
}