local entities = {
    {
        prototype_name = "指挥中心",
        dir = "N",
        x = 126,
        y = 126,
        items = {
        },
    },
    -- {
    --     prototype_name = "科研中心I",
    --     dir = "N",
    --     x = 122,
    --     y = 127,
    -- },
    {
        prototype_name = "小型铁制箱子",
        dir = "W",
        items = {
            {"科研中心I",1},
            {"碎石",100},
        },
        x = 120,
        y = 129,
    },
    {
        prototype_name = "小型铁制箱子",
        dir = "N",
        items = {
            {"破损水电站",2},
	        {"破损空气过滤器",3},
	        {"破损电解厂",2},
	        {"破损化工厂",4},
	        {"破损组装机",3},
	        {"破损铁制电线杆",10},
        },
        x = 126,
        y = 134,
    },
    {
        prototype_name = "小型铁制箱子",
        dir = "E",
        items = {
            {"组装机I",3},
            {"熔炼炉I",2},
            {"液罐I",3},
	        {"水电站I",1},
	        {"蒸馏厂I",2},
            {"机器爪I",12},
            {"小型铁制箱子",2},
        },
        x = 132,
        y = 122,
    },
	-- {
    --     prototype_name = "地下水挖掘机",
    --     dir = "N",
    --     x = 133,
    --     y = 125,
    -- },
    -- {
    --     prototype_name = "组装机I",
    --     dir = "N",
    --     x = 132,
    --     y = 127,
    -- },
    -- {
    --     prototype_name = "液罐I",
    --     dir = "N",
    --     fluid_name = "纯水",
    --     x = 132,
    --     y = 130,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 160,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 159,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 158,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 157,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 156,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 155,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 154,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 153,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 152,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 151,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 150,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 149,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 148,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "E",
    --     x = 147,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-L型",
    --     dir = "E",
    --     x = 146,
    --     y = 132,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "N",
    --     x = 146,
    --     y = 133,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "N",
    --     x = 146,
    --     y = 134,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "N",
    --     x = 146,
    --     y = 135,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "N",
    --     x = 146,
    --     y = 136,
    -- },
	-- {
    --     prototype_name = "砖石公路-L型",
    --     dir = "W",
    --     x = 146,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 145,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 144,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 143,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 142,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 141,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 140,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 139,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 138,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 137,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 136,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 135,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "砖石公路-I型",
    --     dir = "W",
    --     x = 134,
    --     y = 137,
    -- },
	-- {
    --     prototype_name = "物流中心",
    --     dir = "S",
    --     x = 134,
    --     y = 138,
    -- },
}

return {
    entities = entities,
}