local gameplay = import_package "vaststars.gameplay"
local prototype = gameplay.register.prototype

prototype "采矿机I" {
    model = "/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab",
    work_status = {work = true},
    icon = "mem:/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab config:s,1,3",
    check_coord = {"miner"},
    builder = "normal",
    type = {"building", "consumer", "assembling", "mining"},
    area = "3x3",
    drone_height = 42,
    assembling_icon = false,
    power = "150kW",
    priority = "secondary",
    mining_area = "5x5",
    -- sound = "building/miner",
    craft_category = {"矿石开采"},
    speed = "100%",
    maxslot = 8,
    bulk_opt = false,
}

prototype "采矿机II" {
    model = "/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab",
    work_status = {work = true},
    icon = "mem:/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab config:s,1,3",
    check_coord = {"miner"},
    builder = "normal",
    type = {"building", "consumer", "assembling", "mining"},
    area = "3x3",
    drone_height = 42,
    assembling_icon = false,
    power = "300kW",
    priority = "secondary",
    mining_area = "5x5",
    -- sound = "building/miner",
    craft_category = {"矿石开采"},
    speed = "200%",
    maxslot = 8,
    bulk_opt = false,
}

prototype "采矿机III" {
    model = "/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab",
    work_status = {work = true},
    icon = "mem:/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab config:s,1,3",
    check_coord = {"miner"},
    builder = "normal",
    type = {"building", "consumer", "assembling", "mining"},
    area = "3x3",
    drone_height = 42,
    assembling_icon = false,
    power = "600kW",
    priority = "secondary",
    mining_area = "5x5",
    -- sound = "building/miner",
    craft_category = {"矿石开采"},
    speed = "300%",
    maxslot = 8,
    bulk_opt = false,
}

prototype "轻型采矿机" {
    model = "/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab",
    work_status = {work = true},
    icon = "mem:/pkg/vaststars.resources/glbs/miner-1/miner-1.gltf|mesh.prefab config:s,1,3",
    check_coord = {"miner"},
    builder = "normal",
    type = {"building", "consumer", "assembling", "mining"},
    area = "3x3",
    drone_height = 42,
    assembling_icon = false,
    power = "150kW",
    priority = "secondary",
    mining_area = "5x5",
    -- sound = "building/miner",
    craft_category = {"矿石开采"},
    speed = "100%",
    maxslot = 8,
    bulk_opt = false,
}