local DEFINE = {
    FRAMES_PER_SECOND = 60,
    ROAD_YAXIS_DEFAULT = 2.2, -- 路面高度
    PIPE_YASIS_DEFAULT = 6.0, -- 管子高度
}

DEFINE.ROAD_ARROW_YAXIS_DEFAULT = DEFINE.ROAD_YAXIS_DEFAULT + 0.03 -- 路面箭头高度
DEFINE.PIPE_ARROW_YAXIS_DEFAULT = DEFINE.PIPE_YASIS_DEFAULT + 0.03 -- 管子箭头高度

DEFINE.FRAME_INTERVAL_MS = 1000 / DEFINE.FRAMES_PER_SECOND
DEFINE.FRAME_INTERVAL = math.floor(DEFINE.FRAME_INTERVAL_MS / 10)
return DEFINE