local backers = {
    "#Godl1k3-Agomy",
    "--Simon & Josh & Connor--",
    ".tim",
    "0xbaadf00d",
    "0xE1",
    "1ronbank",
    "25DCM25",
    "42persons",
    "7he ODdeST_1",
    "7rus7",
    "8bitjoey",
    "9Diet5Pepsi",
    "=HS= Azzofan",
    "@mtoecker",
    "@RenokK",
    "@TMirroar",
    "@WithinRafael",
    "@xi@g@me",
    "A. Fentress",
    "A.I. \"Penguin\"",
    "Aaron Burns",
    "Aaron D'Arnot",
    "Aaron Dyke",
    "Aaron Powers",
    "Aaron Rose",
    "Aatu Tomas Dean Karjala",
    "ABitAGrease",
    "Abregado",
    "Abronsius",
    "Abusimbel",
    "Acciyn",
    "AcideBurn",
    "Active.Diamond",
    "ADADZEE",
    "Adam Buchan-Wyber",
    "Adam Kuhn",
    "Adam Lawless",
    "Adam Melk",
    "Adam Moyes",
    "Adam N. Hrynewycz",
    "Adragontattoo",
    "Adrian Lucas",
    "AEnterprise",
    "Aerin the Ott",
    "Aerospace",
    "Aether",
    "AFSkeeter",
    "Agent Frogman",
    "Agent MN",
    "Agentfatman",
    "Agoldentheroy",
    "AgriasFabula",
    "Aidan Rooney",
    "Ailure",
    "airtoxin",
    "Aivaria",
    "AJ Kite",
    "Ake",
    "Akeda",
    "Akemi Homura",
    "Akitsuna",
    "Akurosu Arufu",
    "Alan Dingeldein",
    "Alan Guit",
    "Alan Li",
    "alang",
    "Albert",
    "Albert and Chucky",
    "Alberto Chiera",
    "Albtraum",
    "Alec \"ArcticX9\" Belau",
    "Alef Burzmali",
    "Aleksi Postari",
    "Alekthefirst",
    "Alessandro Chizzoni",
    "Alex 'deepy' Nordlund",
    "Alex Assante",
    "Alex Clay",
    "Alex Grube",
    "Alex Hasen",
    "Alex Lee",
    "Alex Meissel",
    "Alex Sashin",
    "Alex Starr",
    "Alex Steiner",
    "Alex Xavier",
    "Alexander",
    "Alexander Becker",
    "Alexander Brüsch",
    "Alexander Ford",
    "Alexander Goncharov",
    "Alexander Grigg",
    "Alexander Harrison",
    "Alexander Hrastic",
    "Alexander Krasnov",
    "Alexander Niketic",
    "Alexander Samylin",
    "Alexander Shepherd",
    "Alexander Simmons",
    "Alexander Spriewald Luciano",
    "Alexander Valys",
    "Alexander W Dawn",
    "Alexei Druganov",
    "Alexis McDavid",
    "Alf Tore Nybakk",
    "Alfred Ilberg Ulvmose",
    "Alfred Vogl Jr",
    "Alfredeus55",
    "Ali Sajid Imami",
    "AliceTheGorgon",
    "Alicius",
    "Aliens Corporation",
    "Alkin Shezar",
    "Allalinor Norix",
    "Allaya Veyo",
    "Allen Dutra",
    "Allen Feng",
    "AllGuy AllMighty",
    "Allison Towers",
    "Almerra",
    "Alviere",
    "alvin8t",
    "Amaterasu112",
    "Amavanola",
    "AmbientKiller",
    "An",
    "An Inn0centBystander",
    "Anakinlawrence",
    "Anane",
    "Anassis",
    "Anders A. Olsen",
    "Anders Find",
    "Anders Parsberg Wagner",
    "Anders Skov",
    "AndiProe",
    "Andre 'Rynam' Steigmeier",
    "Andre Levesque",
    "Andre Pearson",
    "Andreas",
    "Andreas Gerth",
    "Andreas Karg",
    "Andreas Keul",
    "Andreas Mondrup-Hansen",
    "Andreas Roden",
    "Andreas Scholze",
    "Andres Chacon",
    "Andrew \"Frosty\" Dunn",
    "Andrew D",
    "Andrew Davis",
    "Andrew Hobbs",
    "Andrew Macklem",
    "Andrew McKendry",
    "Andrew Reynolds",
    "Andrew Zich",
    "Andrewcol",
    "Andrii Korzh",
    "Androkai",
    "Andy \"Rednic Silversaber\" Deacon",
    "Andy Cormack",
    "Andy Gularte",
    "Andy Ko",
    "Andy Pierpoint",
    "Anelos",
    "AngelAndBobs is hard",
    "Anglermoose",
    "angulion",
    "Angylion",
    "Animar",
    "annih",
    "Anonymous Badger",
    "anoXm",
    "Anthony \"Notething\" Ramsey",
    "Anthony Griffiths",
    "Antoine PLASKOWSKI",
    "Anton Wolf",
    "Antonio Serri :3",
    "Antt Park",
    "Antti Kallio",
    "Anub'i",
    "aoisensi",
    "Apers",
    "Apillia",
    "Aplox",
    "Apoc Dev",
    "Appzolution",
    "Aquamarine Snapjaw",
    "ArachnidXIII",
    "Arathos",
    "ARC19 Industries",
    "Arctic Wolfy",
    "Arend Stührmann",
    "Arganotaut",
    "Argoroth Bantas",
    "Argoti",
    "Ariaxis",
    "Arie Willem van Duijn",
    "Arikast",
    "Arkeia",
    "Arlo Turner",
    "Armadayusx86",
    "Arne431",
    "Arnnost",
    "Aron Groves",
    "Arsin Grünig",
    "Artabz",
    "Artorius Castus",
    "Artua Kassiopi",
    "Arvarik",
    "Arzan Stormrage",
    "As2piK",
    "Aschenborn",
    "Ashen44",
    "Ashkon",
    "Ashley Williamson",
    "Ashser",
    "Asjova McTender",
    "Aske Lyngbak Hansen",
    "AssaultRaven",
    "ata",
    "Atero Dirotsky",
    "Athan Falangus",
    "AtomLegend",
    "Atreu",
    "Atruvai",
    "Atspulgs",
    "Attar Caldero alias M.Rzonca",
    "Attila Pfeiffer",
    "AunOTauShi",
    "Auran Fox",
    "Auran Taufa",
    "Austerian",
    "Austin McDonald",
    "Austin Pellowski",
    "AustrianDemon",
    "Austvoll!",
    "Austyn Rivera",
    "Ausveikus",
    "Avendium",
    "Aves",
    "awesome guy 9001",
    "AwesomeS",
    "Awesomesauce",
    "Axel Vanoni",
    "Axle Gear",
    "AyrA",
    "Aza Industries",
    "Azaah",
    "A_Dragon_Killer",
    "B.E. Westerbaan",
    "Baalem",
    "Badefuzzi",
    "Bad_Bach",
    "Balckhand",
    "Baldur",
    "Balthazar",
    "BammBamm Rubble",
    "Bananabear_Jr",
    "Bangz",
    "BanHammer",
    "Baron Vladimir Harkonnen",
    "Barry J. Niepokny Jr",
    "Bart de Ruijter",
    "bartoua",
    "bar_k60",
    "Bas Kievits",
    "Baser",
    "bassmans",
    "Bastian -Lancer- Forster",
    "BattledroidB3",
    "beamer91",
    "beankappa",
    "Beany",
    "Beatron",
    "Becky Dobson",
    "Bedders",
    "begebot",
    "Ben Battersby",
    "Ben Colijn",
    "Ben Cross",
    "Ben Edger",
    "Ben Page",
    "Ben Pierce",
    "Ben White",
    "Benedetto Nicolas",
    "Benedict",
    "Benedict Roeser",
    "BenFisher3148",
    "Bengt-Göran Persson",
    "Benjamin Hall",
    "Benjamin Hausch",
    "Benjamin Keene",
    "Benjamin Kitchen/CatPotato",
    "Benjamin Lewis",
    "Benjamin Mussche",
    "Benjamin Reichstein",
    "Benjamin Schellenberg",
    "Benjamin Schmid",
    "Benjamin Stanwell",
    "Benjamin Wasem (Dei Mudda Space)",
    "Benjamin Zeigler",
    "Bennet Bleßmann",
    "Bennett Stain",
    "berezinik",
    "Bergie",
    "Bert Cypress",
    "bfgmetalhead",
    "BiFiK",
    "Biggkahuna",
    "Biksu",
    "Bilka",
    "Billy Gallagher",
    "Billy-J",
    "Binarium",
    "Binaryblade",
    "Binilman",
    "Biotronic",
    "Birdlay",
    "Bisa",
    "Bishop",
    "Bitcoin",
    "Bjoern Bu.",
    "Bjorn Verzijlbergh",
    "Björn 'Pheenics' Heesemann",
    "Bjørn Gustav Baklid",
    "BL",
    "Black Magix",
    "Black Mamba 666",
    "Black Sunday Rock",
    "Blackem",
    "blackhawk120",
    "BlackNova",
    "Blackphidora",
    "BlackSheep(.im)",
    "BlackSilent",
    "Blady Waterflower",
    "Blain Crighton",
    "Blake Horn",
    "Blake Mattingly",
    "Blake Reinhart",
    "Blakeslee Bür",
    "Blazda",
    "BlitzProg",
    "Blkdragon112",
    "bllrdryn by SEV sub",
    "blooddrunkreaper",
    "Bloodlars",
    "BloodScourge",
    "Blood_Seeker_00",
    "Blowtorch",
    "Blue Frostfire",
    "Blü",
    "bmearl4",
    "Bob Fizzle",
    "Bob Machacek",
    "Bob Tucker",
    "Bobby Fender",
    "Bobby Renard",
    "Bobingabout",
    "BobMcKnob",
    "Bocator",
    "Boebia",
    "Boerd Groundmaster",
    "BOF007",
    "Bojangles",
    "Boltyhead",
    "Bonenash",
    "boogieman",
    "BoozleBox",
    "borgx",
    "Boss Bravo",
    "Bossheus",
    "Bouncebag",
    "Bounty Da Hunta",
    "Bowlympicshero",
    "bpreece83",
    "Brad Stone JR",
    "Brambor",
    "Brandon Jasper",
    "Brandon Kallam",
    "Brandon Kelly",
    "Brandon Kim",
    "BreadWave",
    "Brendan McBride",
    "Brendan Rood",
    "Brenton Smith (thestsp)",
    "Bret Campbell",
    "Brett W",
    "Brian 'Newb' Reichenbach",
    "Brian (Kaylei) and Kaitlyn Dromgoole",
    "Brian Huth",
    "BriceGdT",
    "Briezee & Fizziii",
    "Bromoc",
    "Bryan Arnold",
    "Bryan Braunschweig",
    "Bryan Glen Richards",
    "Bryan Pardy",
    "Bryant Chang",
    "BT_Viking",
    "Bubba Swag",
    "Buche",
    "Buckerneir",
    "bugg94",
    "Buggs K100RS",
    "build_me_baby_one_more_time",
    "Bulba",
    "bunq",
    "burning",
    "Busterguy",
    "Butterfly",
    "Butters Furry Party",
    "Bwana McCall",
    "bwizzle",
    "Byrdmanevil",
    "C.J. Carter",
    "Cain Carter",
    "Caj \"FlipJaxx\" Tidemandsen",
    "Cakengrad",
    "calcifer",
    "Caleb and Molly Shotwell",
    "Caleb Wood",
    "Calissa Squid",
    "Callesimo",
    "Callie Arnadottir",
    "Callum McCann",
    "Calum Bromley",
    "Calvin Greiling",
    "Cameron Collins",
    "Canadian Neighbour",
    "CandyDemon",
    "CapnDrinksCapn",
    "Capt. Kim \"Salty\" Mockett",
    "Captain Midnight",
    "captainbritain",
    "CarFlashen",
    "Carline",
    "Carrick Greenmere",
    "CarryGupta",
    "Carzak",
    "Casey C. Knowlton-Key",
    "Casey Campbell",
    "Cathril",
    "catt0",
    "Caulis Brier",
    "cbdev",
    "Cecota",
    "Cedric Floréal",
    "Cedric Suzuki",
    "Celazer",
    "Celebloki",
    "Cephira",
    "Cerous",
    "Chad 'Innovate' Dillman",
    "Chad Bramwell",
    "Chaircorp Inc.",
    "Chance Alford",
    "Chancellor87",
    "Chani Atreides",
    "Chaosmachine420",
    "ChaosOptional",
    "Chargeraider",
    "charles gangloff",
    "Charles Gordon",
    "Charles Nolder",
    "Charles Sanders",
    "Charles W. Stanton",
    "Charles-Antoine Duval",
    "Charlie Overly",
    "Charls Ruebenbauer",
    "Charly Stark",
    "Charon",
    "Chase L.",
    "Chase Xavier",
    "Chasen Ayers Miko",
    "Chaz",
    "Chaz Blackston",
    "Chaz Serir",
    "Cheekytms",
    "Cheetah",
    "ChickenRunsWild",
    "Chilly smeez :)",
    "Chinchilla",
    "Chinmay Garde",
    "Chipolux",
    "Chiron_Chen",
    "Chorescore Me",
    "Choumiko",
    "Chralex",
    "Chris \"Combat_Zerg\" gudmundson",
    "Chris \"The Nooblord\" Sheneman",
    "Chris Brauer",
    "Chris Britton",
    "Chris Clayton",
    "Chris Cullup",
    "Chris Fischer",
    "Chris Thoreson",
    "Chris Willetts",
    "Chrischi",
    "chrisdttn",
    "Christiaan Burchell",
    "Christian Hilbrands",
    "Christian Jacobsen",
    "Christian Kajsing",
    "Christian Sanchez",
    "Christian Sperber",
    "Christian Telefont",
    "christianleo333",
    "Christof Cieslik",
    "Christoffer Bech",
    "Christoph Schütze",
    "Christophe ALVES",
    "Christopher 'Alduin' Bock",
    "Christopher Bejune",
    "Christopher Conforti",
    "Christopher Daniel Draper",
    "Christopher Daniel Rij",
    "Christopher Greene",
    "Christopher R. Kettle",
    "Christopher Schank",
    "Christopher Trent",
    "christopher willings",
    "Christophpher Hendriksen Lindeberg",
    "Chuckles",
    "Cidzero",
    "Cirno",
    "Cirrial",
    "Clawlesskurt",
    "Clay Sloan",
    "Clemens Zelt",
    "Cliff Richardson",
    "clouths",
    "ClubPetey",
    "Clutchizzle",
    "CM Johnson III",
    "CMDR CPY",
    "CMDR Von Dovic",
    "Coalfoot",
    "CobaltCore",
    "Cody Cozad",
    "Cody R. Taylor",
    "Coestar",
    "COHL - 7500 Co.",
    "Colin Haber",
    "Colin Hoffman",
    "Collin \"Cavah\" Van Horn",
    "Collin Reeves",
    "Colonel Will",
    "Combatdude",
    "Commander Neverborn",
    "Commotionsocks",
    "CompileNix",
    "ComputerBaer",
    "Compwiz1548",
    "ComradeNixco",
    "Condo",
    "Conj",
    "Conn",
    "Connor \"EightTimesNine\" Richards",
    "Connor Doornbos",
    "Connor Hildebrand",
    "Connor Hollasch",
    "console0",
    "Contesul",
    "Convieo",
    "Coopalan Enterprises",
    "Cooper M",
    "Coralai Generous",
    "Corentin Gire",
    "Corey Yllander",
    "Corn6269",
    "Corneliu Vasiliu",
    "Coslany",
    "CosmicFish",
    "CoStar",
    "CounterAgent",
    "Cowmen",
    "CowTrap",
    "CPL Taylor",
    "Cpone",
    "cptbob",
    "CraftBattleWoof",
    "Craig 2.0",
    "Craig Barrett",
    "Craig Samson",
    "Crantzbea",
    "Crazieman",
    "Crazy Dimensions",
    "CrazyMack",
    "Creegor",
    "CreeperHost LTD",
    "Creighton K. Yanchar",
    "Crellas",
    "Crepuscolo",
    "Cretox",
    "CrimzonWolf",
    "Cristian Ares",
    "Croebh",
    "Crumble_Z",
    "Crusader8389",
    "CrushedIce",
    "Cruster",
    "CTaiger",
    "cube",
    "CubeFanGaming",
    "CuddlyFlower",
    "CumaTrOOp",
    "Curtis Agnew",
    "Curtis Stalesky",
    "Cussler80",
    "Cyclone Husker",
    "cycloptivity",
    "CynicalRayzor",
    "cyphercat",
    "Cypherpunk",
    "Cyric the Nalarian",
    "Cyrikyty",
    "Cyril Labitte",
    "Cyril wer Kaldra",
    "D Gregory",
    "D Johnson",
    "D. R. Bauer",
    "D.J. Brown",
    "d4rkpl4y3r",
    "Daan de Rond",
    "Daan van de Craats",
    "Daedalus Storm",
    "Daehreck Lavendahl",
    "Daffy",
    "DaistarMC",
    "Dakkanor",
    "Dalacore",
    "Damage",
    "Damian Mulligan",
    "Damien spaans",
    "Damrote",
    "Dana Hanna",
    "Dana Mahar",
    "Dandistine",
    "Dane Sucre (Sparkz)",
    "DaneWW",
    "DanGio",
    "Daniel \"Hexatron\"",
    "Daniel \"Joogi\" Graban",
    "Daniel (Schorty) Schlenger",
    "Daniel Ackermann",
    "Daniel aka \"Gecko\"",
    "Daniel Bone",
    "Daniel Carlin",
    "Daniel Espelid Pedersen",
    "Daniel Harmsworth",
    "Daniel Jack",
    "Daniel Johns",
    "Daniel Kennamore",
    "Daniel Ledger",
    "Daniel Loddeke",
    "Daniel Mann",
    "Daniel Mußmann",
    "Daniel Stoffel",
    "Daniele Santoru",
    "Daniel_YC",
    "dankmonkey",
    "Danny Beedle",
    "Dantanian",
    "DapperAeronaut",
    "DarAiel14",
    "Darek Vrnak (CZ)",
    "Dark Zeak",
    "Dark3ven",
    "darkice",
    "Darknakine",
    "Darkshadow395",
    "Darksheer",
    "DarkusAlpha",
    "Dark_Technician",
    "Darren Carow",
    "Darren Simmons",
    "Darren Sprudd",
    "Darryn Pierce",
    "Darth Revan",
    "Dartus33",
    "Darwerft",
    "Daryl Crew",
    "darzon wuxian",
    "Daskar",
    "DasSaffe",
    "Daszh the Fox",
    "Dat_Panda_en",
    "Dave Hart",
    "DaveKap",
    "David Bermingham",
    "David Francis",
    "David L Jones",
    "David Lees",
    "David Leslie",
    "David Lin",
    "David Marteney",
    "David Martens",
    "David O'Connell",
    "David Ryder",
    "David Skrundz",
    "David Stritzl",
    "David Wahl",
    "David Willoughby",
    "David Y Oh",
    "David123450",
    "Daxxtramuss Hunt",
    "Dayhalk",
    "daznet69",
    "DDraig",
    "De Loeul",
    "Deadly Night",
    "Deadlykillbot",
    "deadlypineapple",
    "DeamonEngineer",
    "Dean \"Rocket\" Hall",
    "DeathLichWIng",
    "Deathmic",
    "Decepere",
    "Declassified",
    "Deetydoc",
    "Defender833",
    "Defianz",
    "Defty83",
    "Dega Dahega [Magix39]",
    "Delaney Tenebrae",
    "delaytime0",
    "Deli_SK",
    "DeloGazi",
    "Delskey",
    "Delta_Osiris",
    "Dema",
    "Demi Viral",
    "dEmindED",
    "Demonicwolf9",
    "Den Sckriva",
    "Dengo",
    "Dennis \"Hetfield\" Winkelmann",
    "Dennis Glebe",
    "Dennis Holmén",
    "Dennis Iwan Slisser",
    "Dennis Overbeek",
    "DennisH",
    "dennisw100",
    "Der Gallier",
    "Derm",
    "DerTolleIgel",
    "Deshment",
    "Desmont",
    "Dev-iL",
    "Devenias",
    "DevilAngel25",
    "DevilKhan",
    "DevilLordSix",
    "Devin De Frisco",
    "devjock",
    "Devon J",
    "Devon Lavoie-Trites",
    "deWulf",
    "Dexcuracy",
    "Dexxa",
    "dgonn",
    "dharh",
    "Diabolical Demons",
    "Digedog",
    "DigiSlug",
    "DigitalBlight",
    "Dimitri Bauwens",
    "Dimitri Pirio",
    "Dina Holmen",
    "Dine Frosty",
    "Dininy",
    "Dinnerbone",
    "Diogo Lopes",
    "diphtherial",
    "Direform",
    "Disaster Area",
    "DivingEveryDay",
    "DixieFire",
    "DJFLuFFy vs joe",
    "DJRodrigo",
    "Dmitry Blotsky",
    "Dmitry KoDi Kotlyar",
    "doberlec",
    "Dobri",
    "DocPhiro",
    "DocShoe",
    "Dolinmyster",
    "Dolpe",
    "Dominic B",
    "Dominic Behlau",
    "Don Pinkster",
    "Donald Chonko",
    "Donald E. Richardson III",
    "Donbo",
    "Dougl07",
    "Douglas Greer",
    "Douglas Meyer",
    "Douglas S.M. Lum",
    "Downtime",
    "Dr Sean",
    "Dr Venku",
    "Dr Wiesmann",
    "Dr. \"Pinky\" Brink",
    "Dr. Benjamin",
    "Dr. Freaky Okle",
    "Dr. Gravitas",
    "Dr. Strangethumb",
    "Dracorex",
    "Dracule",
    "Drago100ful",
    "Dragon Nemerod",
    "Dragondark De Lonlindil",
    "Dragonlord64",
    "DragonMaus",
    "Dragonslayer Taz",
    "Dragonster16",
    "DragonV2",
    "Dragoon2103",
    "Drake Aradian Parker",
    "Drake R. Dennison",
    "Dreamreaver23",
    "Dredge",
    "Drew 'Darklight' Edgar",
    "Drew SR Damon",
    "DrHerpaDerp",
    "DrHorrible",
    "Drifton Aloft",
    "DrittaFull",
    "DrJns",
    "DrMoebyus",
    "drone",
    "drs9999",
    "Drullkus",
    "Drunk3n_Dr4g0n",
    "Drury",
    "Dr_LegoWolf",
    "Dré Kozar",
    "DSoS",
    "Duane Glassco",
    "Duane Sibilly",
    "Duke Al",
    "Duley",
    "DumperJumper",
    "Duncan S",
    "Dunstrum",
    "Dupl3xxx",
    "Durmij",
    "Dustician",
    "Dustin Hendee",
    "Dustyn Bartlett",
    "Dylan Rawe",
    "Dylan112",
    "Dynar Nastor Areus",
    "Dysoch",
    "E-Kyozyu",
    "Eastborn",
    "Echo Calypso",
    "Echosa",
    "EclipsedWraith",
    "Ed Funke",
    "Ed Oliver",
    "Eddie Shrubsall",
    "Eddie Wafru",
    "Eddy Lu",
    "EDMEbba",
    "edorian",
    "Eduard Miskevich",
    "Edward Massey",
    "Edwyn Tiong",
    "Egan Loughran",
    "EGCSvetiKruh",
    "Eiche",
    "einboeserZwilling",
    "Eirik \"Trapdoor\" Haarberg",
    "Ekhari",
    "Ekir Atari",
    "Eklund",
    "Elangeswaran",
    "eLbot",
    "Elcajon",
    "ElCyClOpE",
    "Electric Spark",
    "Eleftherios",
    "ElenaRoan",
    "Elijah Menifee",
    "elite_mus",
    "Ellefsen",
    "Elliott Brown",
    "Elliott Holt",
    "Elmo Relaxo Niklas Eichornchen Bitsch",
    "ElreyForce",
    "Elysium_81",
    "Emily.",
    "emogreen",
    "EmpiricalPython",
    "Emraldine",
    "Emrik Hydén",
    "Ender Souza",
    "Enginseer Sethicus",
    "Enmel",
    "Enocm",
    "Enrico Frehner",
    "Eoin Joy",
    "Eon Atta",
    "Eran Kovacs",
    "Erdnusschokolade",
    "Eric Duncan",
    "Eric Floehr",
    "Eric Goldsmith",
    "Eric Parry",
    "Eric Rasnier",
    "Eric Sexton",
    "Erik Haßlmeyer",
    "Erika Santiago",
    "Errorsnake",
    "Eruestani",
    "Erus_Iluvatar",
    "Esa Kleemola",
    "Esculator",
    "Eskode",
    "Ethan",
    "Ethan",
    "EthanCGamer",
    "Ethlaron",
    "Euan Andrew",
    "Eunky",
    "EvanR",
    "Eviber",
    "Evil St John",
    "Ewan Spence",
    "exi",
    "Exodes",
    "exotwist",
    "Eyamaz",
    "Ezrixus of the Unforgiven",
    "F.Yavorskiy",
    "FaaNavnIgjen",
    "Fabien Romano",
    "Fabio Lutzu",
    "Factory Man #001",
    "Fadetoblk27",
    "Fahrplan",
    "Fajita Puppy",
    "Falch",
    "Falcon Darkstar",
    "Falke",
    "Falorin",
    "Family Gildersleeve",
    "Fantasic",
    "fanyu",
    "Farenjihn",
    "Fargutin",
    "Faro",
    "Fasmic",
    "FatMcK",
    "Fatmice",
    "Fattymac",
    "Faxel",
    "Fearsomecake",
    "Felextheminimal",
    "Feline-Biologist",
    "Felipe Milioni",
    "Felix Code",
    "Felix Esser",
    "Felix Fichte",
    "Ferdinand Marques",
    "Ferote",
    "Field Command",
    "FightBack",
    "Final Affliction",
    "Finn Ejsing",
    "firebreaker2262",
    "Firestar311",
    "Firewolf",
    "Fkscorpion",
    "Fl@sh",
    "Flagbyrd",
    "Flakk_Munky",
    "flamehead4",
    "Flandre Scarlet",
    "Flare Shift",
    "flaydo",
    "Flip",
    "Fliper333",
    "Flitzx",
    "Florian",
    "Florian Dussault",
    "Florian Maunier",
    "Florian Michael Busch",
    "Florian1024",
    "Flovara",
    "Flunkus",
    "Flutterguy",
    "Fluttershy",
    "Flying Wolf",
    "Flying_Odobenus",
    "FlynnGoesNoob",
    "ForceSpirit",
    "forgingbanana",
    "Foster Davies-Smith",
    "FoxFerro",
    "foxtrotV",
    "Foxx",
    "Foxxonius Augustus",
    "fraggdya",
    "Frail",
    "Franc",
    "Francisco Cavieres",
    "Frank Zichner",
    "Frankenfrank",
    "Franz Wernicke",
    "Fratz",
    "frazor's den",
    "Frecki",
    "Fred Nilpferd",
    "Freddie \"Mormonjesu8\" Gray",
    "Frederic Roy",
    "Frederik 'Pino' Rasmussen",
    "Frederik Folkvardsen",
    "fredigar",
    "Fredrik (Poparen) Dahlin",
    "FreeER",
    "Freeism Saurfang",
    "Freemen89",
    "Freya Fairwing",
    "Freyman90",
    "Friederich Mensing",
    "Frisbie",
    "Frit0z",
    "Frithjof Berger",
    "Fritze",
    "Friðrik Ómar Erlendsson",
    "FRodrigues",
    "FrustratedPotato",
    "Frédéric Van Overmeeren",
    "fshnyak",
    "Fubar",
    "Fung Fan",
    "Funnynin",
    "fuseji",
    "future",
    "FyredUp",
    "Félix Poitras",
    "Gabe Connor",
    "Gabriel Wrede",
    "Gadarol",
    "Gaetan D",
    "Galud",
    "Gameonlp",
    "Gamer045",
    "Gamerofgold",
    "Games4Kickz",
    "Gamesmig",
    "Gamingdaredevil",
    "Gandir",
    "Gangrel85",
    "Ganz Rig",
    "Garbfink",
    "Gareth Slade",
    "Garett \"Frezo\" Leitner-Ehmann",
    "Gargish",
    "Garrett Shaffer",
    "Gart",
    "GateKeeper",
    "GauntletWizard",
    "gcoguiec",
    "Gdelic",
    "Gecko Industries",
    "Geekme",
    "Gelly",
    "Gen2Chiro",
    "General Disarray",
    "General Disaster",
    "GeneralSnipe",
    "GeneralZero",
    "General_Cell",
    "genericname1",
    "Genezz",
    "Geoff Lloyd",
    "Geordi La Forge",
    "George Gibbs",
    "George Haslett",
    "George Neaves",
    "George Padolsey",
    "Geostyx",
    "GerCasta",
    "Gergith",
    "Gergő Ládi",
    "Germanfragger",
    "Gerrycane",
    "Gerwin Bergsma",
    "GHaKK",
    "Ghost",
    "gHoST INFERNO",
    "Gianluca",
    "Giantdwarf",
    "Gibbs",
    "Gilbatron Heavy Industries",
    "gildeddiamond",
    "gino van de graaf",
    "Givup",
    "Gizmotin",
    "Gjertsens kebab, taksidermi og landhandel",
    "glacia",
    "Glibweshump",
    "Glubo",
    "Gnapouille",
    "Go Play Ultimate Frisbee",
    "Godfatherbobo",
    "Goldkoloss",
    "Goochnasty",
    "good will",
    "Goof & Boof",
    "Goosemopod",
    "GordonGaz",
    "Gorfinhofin",
    "Gothicmj666",
    "gothroach",
    "Gotterdammerung",
    "Grafas De Jurko",
    "Graham Summerhayes",
    "grandrolf",
    "Grant \"Sin\" White",
    "Grapejelly",
    "Gredalor",
    "Greedseed",
    "Greenacre",
    "Greg Buzarde",
    "Greg Hardy",
    "Greyson Brewer",
    "Grille79",
    "Grim the Red",
    "grimmeld",
    "groovestreet",
    "Grubberdeck",
    "GuardIan4220",
    "gudenau",
    "Guillaumeb810",
    "Guitargun",
    "Gukinator",
    "Gundaroes",
    "GunerV9",
    "Gungun974",
    "GunnmarGaming",
    "gunsmoke162",
    "Guo Li \"Arowana\" Xiao",
    "GUT417",
    "Guy Moreau",
    "Gylfi Runarsson",
    "Göran Nehlin",
    "Günter",
    "Habadacus",
    "Hackempluf",
    "haho",
    "Haidy777",
    "Haiwei",
    "Hamburgers",
    "Hammond",
    "Handzor",
    "Hans Dietrich",
    "HanSolo0001",
    "HanziQ",
    "Han_Soo_Choi",
    "HarbingTarbl",
    "Hardison",
    "Harold Feit",
    "Harris J Smistad",
    "Harry736",
    "Hartsworth",
    "Hasselpoof",
    "Havick",
    "Hawk",
    "Haydn Davis",
    "Heidi Hokka",
    "Heinrich Moritz Matthaeus Goedeke",
    "Heldis Anderson",
    "Hell Fire",
    "Hellabadass",
    "Hellberg",
    "HellHelpMe2000",
    "Helliqwyn",
    "Hellkith",
    "HellWatcher",
    "Helmi",
    "Hendrik Lindemann",
    "Hendrik Wilka",
    "Henrik Hagen",
    "Henrik Hillefors",
    "Henry H Plauche IV",
    "Henry T Woods",
    "Hercegovac Christian",
    "HerobrineTheAT",
    "HeroUltraOmega",
    "Herr_Razor",
    "Hexicube",
    "Hi-Torque",
    "highkeji",
    "Hillomunkki",
    "hippi5",
    "Hiul Dragonfel",
    "Hjorvir",
    "Hobbyte",
    "Hogan Long",
    "Hokan",
    "Holgast",
    "Holy-Fire",
    "Honeycake",
    "Hong Kong",
    "Hookguin",
    "Hord of the Flies",
    "Hoss9900",
    "Hubble Inc.",
    "Hubert K",
    "Huddlebunny",
    "Hudifah Rabie",
    "Huggles",
    "Hugorm",
    "Hunter Lavallee",
    "Huryiade",
    "Huw45",
    "Huwster1111",
    "Hvass",
    "Hybertz",
    "HyenaGER",
    "Hyomin Broxxi",
    "Hyrulepost",
    "Hyu Jacobi",
    "hyvamiesh",
    "Håkon A.",
    "I am Different",
    "i like trains",
    "IAMGR00T",
    "Ian Charboneau",
    "Ian Clark",
    "Ian Coop",
    "Ian Knowles",
    "Ian Malik",
    "Ian Parker-Ross",
    "iCart",
    "Iced",
    "Icehockeyplyr",
    "Icemanking",
    "icharus2099",
    "Ichqwertzu",
    "iconiuss",
    "IcyKoala",
    "IcyMidnight",
    "IdioticUlt1mara",
    "ienAri",
    "Iessa Pragg",
    "Ignat Zoin",
    "Igor Timurov",
    "Ikaria",
    "Ikeda Kenichi",
    "ILLiardVonBeck",
    "Imhotep Jones",
    "immer",
    "ImPa",
    "in disguise",
    "inc0gni10",
    "Indras",
    "Inferndragon",
    "infernoid",
    "InfinitySamurai",
    "InflatableBeerTent",
    "Infuso",
    "Ingenium86",
    "ingie",
    "Inkie",
    "Inogames",
    "Inverted Moongoat",
    "Invisible",
    "Ioannis Gabrielides",
    "Irdy",
    "iroha",
    "IronCladMoon",
    "IrrelevantScrub",
    "is full of bees",
    "is on fire",
    "Isaac Robitaille",
    "Isdar",
    "Isthiriel",
    "itzillegal(aka omega)",
    "Ivo Elezovic",
    "iwanbok",
    "J'Poll",
    "J,Schoenmakers",
    "J-Hoppa",
    "J. Miramontes",
    "j3007g",
    "Jabberwokin",
    "Jabbslad",
    "Jacek Kałudziński",
    "Jack Arnold",
    "Jack Chisholm",
    "Jack Domenici",
    "Jack Edwards",
    "Jack Helsby",
    "Jack Odom",
    "jack raynor",
    "Jack Stanbridge",
    "Jackal13Antern",
    "Jackalope",
    "Jackflash3r",
    "Jackson Edick",
    "Jacob \"dorn284\" Niederkorn",
    "Jacob Bickle",
    "Jacob Creasey",
    "Jacob Fresh",
    "Jacob Lichtefeld",
    "Jacob M. Holm-Christensen",
    "Jacob5263",
    "Jacquy Hugo",
    "Jaden",
    "Jagged Edge",
    "Jak D'Bin",
    "Jake",
    "Jake Carney",
    "Jake Parr",
    "Jake Tereau",
    "Jake Wooten",
    "Jakelock52",
    "jakimfett",
    "Jakob Lindgren",
    "jakob tøtterup tranbjerg jensen",
    "Jam-Jam",
    "James 'Buddy' Bray",
    "James A. Bond",
    "James Chadders",
    "James Clarke",
    "James DeMeuse",
    "James McLean",
    "James Neale",
    "James Nicholas",
    "James Peck",
    "James Polley",
    "James Roshal",
    "James Shield",
    "James Sorenson",
    "James Swandale",
    "James Van Toorn",
    "james12802",
    "Jameson Shaffer",
    "Jamie Alex Johnson",
    "Jamie Hayes",
    "Jamie Lawson",
    "Jan Bremer",
    "Jan Henning Haas",
    "Jan Notka",
    "Jan Pircher",
    "Jan Půst",
    "Jan R Ward",
    "Janar Kaseorg or Jax0K",
    "Jango Fish",
    "Janice \"LondonGirl\" Whitson",
    "Janko \"jenx\" Cretnik",
    "Janne Pihlajaranta",
    "Janne Salminen",
    "Janzo",
    "Japhet",
    "Jared \"deafgeek\" Jonas",
    "Jared Goodspeed",
    "Jari Koivisto",
    "Jaroslav Pialek",
    "Jasi246",
    "Jason C Rogers",
    "Jason Elliott",
    "Jason Scrivens",
    "Jason Swisher",
    "Jason Widdy",
    "Jason Winstanley",
    "Jasper Dirza Olthof",
    "Java",
    "Jay Henneberry",
    "Jaycee Pyne",
    "Jayde Baldwin",
    "Jayden Staszewski",
    "Jayers2",
    "Jayjader",
    "Jayzus",
    "Jean Paul Lemoine",
    "Jean Sebastien Chasle",
    "Jean-Marc Nielly",
    "Jecks",
    "Jeffersah!",
    "Jeffrey de Brouwer",
    "Jeffrey Malone",
    "Jeffrey Scheepbouwer",
    "JeFo",
    "Jelle Meersman",
    "Jens Bennauer",
    "JensK",
    "jep14",
    "jercos",
    "Jeremiah A. Coley",
    "Jeremiah Fitzmartin",
    "Jeremiah Roach",
    "Jeroen van de Coterlet",
    "Jerome2103",
    "jeroon",
    "Jesper G. Nielsen",
    "Jesse Smith-Rogers",
    "Jesse Suhonen",
    "Jestinu",
    "Jesus Friel",
    "Jesus Perera Aracil",
    "jetEnergy",
    "JETX9300",
    "Jevgenijus Gribas",
    "Jezynka",
    "Jhonofretro",
    "JimBer110",
    "Jimmidii",
    "Jimmy Goossens",
    "Jiseng So",
    "JKDEM85",
    "Jo Krister \"Joker\" Simones",
    "Joachim",
    "Joakim Nilsen",
    "Joaquim Ortiz Gomez",
    "Jochem (Blondie) 285",
    "Joe \"TJ\" Jones-Johnson",
    "Joe Bacon",
    "Joe Cannon",
    "Joe Crosby",
    "Joel Croteau",
    "JOEPM25",
    "Joey Corless",
    "Joey Wilder Justiss",
    "Johan Wiberg",
    "Johannes Bæk",
    "John Castle Britton",
    "John Connell",
    "John E Garvey III",
    "John Fitzpatrick",
    "John Hyland",
    "John Loftus",
    "John Rogalski",
    "John Whittle/Wolveneclipse",
    "John-Andreas Lorentzen",
    "Johnathan Rigel",
    "Johnathan Roberts",
    "Johnny Wünsch",
    "johnnygs",
    "JohnyCilohokla",
    "JohnyCnUpT",
    "Jolion Norse",
    "Jon Allan",
    "Jon Such",
    "Jon V. of Norway",
    "Jonah Shafran",
    "Jonas Fladset Hoel",
    "Jonas Jørgnsen",
    "Jonathan (AKA Sandia) Erlandsson",
    "Jonathan Brunath",
    "Jonathan Gillette",
    "Jonathan H.",
    "Jonathan Oliver",
    "Jonathan Reseigh",
    "Jonathan Stewart",
    "Jonathan van Houten Fontoura",
    "Jonathon Banks",
    "Jonny M",
    "joram pater",
    "jordan bailey",
    "Jordan Grinde",
    "Jordan McBride",
    "Jordan Sallans",
    "Jordan Schaller",
    "Jordan30001",
    "Jorik Seisveld",
    "Jorji Cobrastan",
    "Josef Šibrava",
    "Joseph \"MeisterJoe\" Jackson",
    "Joseph G Dean",
    "Joseph Hall",
    "Joseph Lynch",
    "Joseph M. Bascetta",
    "Josh Sheep",
    "Josh Sorensen",
    "Josh415",
    "Joshua Beale",
    "Joshua Himing",
    "Joshua Proctor",
    "Joshua Starkman",
    "Joshua Travis Horton",
    "Joshua Vangilder",
    "joshxman",
    "Joss J Smith",
    "Joviah",
    "Juan A Gonzalez",
    "Juho Kuosku",
    "Julian \"Jolle\" Paul",
    "Julian Platnar (The Best Ever)",
    "Julian Stoesser",
    "Julianna",
    "Julien Beauduffe",
    "Julien Ngo-Gaston",
    "julien paton",
    "JulienMaster",
    "Julius \"onewithname\" Bezaras",
    "Julius Körber",
    "Junny2233",
    "Juraj Hrinik",
    "Justin Briard",
    "Justin Ramos",
    "Jérémie Fery",
    "Jóhann Smári Guðmundsson",
    "JyeGuru",
    "K-DaK",
    "k1ne",
    "K54",
    "kaathewise",
    "Kacper Wronka",
    "kadira",
    "Kai Simen Samuelsen",
    "kajak96",
    "Kajinama",
    "Kalabint",
    "Kalazar",
    "Kaluki",
    "Kanweas",
    "Kappa",
    "Kardlonoc",
    "Karmgahl",
    "Karosieben",
    "Kasslim",
    "Kasuko",
    "Katherine Rooney",
    "Katie Leach",
    "Kato Andre Ulevik",
    "Katsumbra",
    "Kayanor",
    "Kayron",
    "kayspee",
    "kds71",
    "Keel Lassche",
    "Keksmann",
    "Kela Kai",
    "Keldor",
    "Kellan Cotter",
    "kellerkindt",
    "Kemtari",
    "Ken T",
    "Kenakapheus",
    "Kenneth Rosario",
    "Kenny Ordonez",
    "KENT",
    "Kent Eriksen",
    "Kerberos",
    "Kerby Stoudt",
    "Kerna",
    "Kero",
    "Kerry Melton",
    "Kevin \"Shaymes\" Bauermeister",
    "Kevin 'Byter' Becker",
    "Kevin Brennan",
    "Kevin Hoeppner",
    "Kevin L. K.",
    "Kevin Leonhard Haugen NOR",
    "Kevin McKenzie",
    "Kevin Rugland",
    "Kevin Shanahan",
    "Kevin Stork aus Telgte",
    "Kevin128",
    "Keyboardhack",
    "KeyszerS",
    "Khaim",
    "Khalidus",
    "Khalysto",
    "Khyron",
    "Kial Morgan",
    "Kiddi Kristjans",
    "Kieran Uttley",
    "Kiichiro",
    "Killerskulls636",
    "KillerWL",
    "Kilronis Daerqueside",
    "Kim G Jensen aka Tnts120",
    "Kim Jong il",
    "Kim Parkkinen",
    "Kim Schmid",
    "Kim, Joon",
    "kimett",
    "King Lemming",
    "King of Tao",
    "kingoffactorio",
    "KirjoZzZ",
    "Kirmari",
    "Kirsendarken",
    "Kisha",
    "Kiska",
    "Kithop",
    "Kjetil Menkerud",
    "Kjevo",
    "KKjoon",
    "kkofmel",
    "KlaSta",
    "Kleimon",
    "Kleinig",
    "Klopfer",
    "KngSolomon13",
    "KnightCat",
    "KnightHarm",
    "KnightRath",
    "KnightsEmbrace",
    "Knivesron",
    "Knocks",
    "Knorr KycklingKrydda",
    "KNOWFEAR1337",
    "Knurps",
    "Kodemikkel",
    "Kodi Anderson",
    "Kody Holsen",
    "kody mullins",
    "Koichiro 'mego' Oishi",
    "Kokkarinen",
    "Kom the Dragon Enthusiast",
    "Konair Konairius",
    "Konstantin Kuderko",
    "korneel vandamme",
    "Kortako",
    "Kotasienka",
    "Kotomata",
    "Koub",
    "Krakenbrau",
    "Kramer",
    "Krapht",
    "Krazon",
    "Kristian Adolphsen",
    "Kristian Leuthold",
    "Kristof Vannotten",
    "Krombopulos Michael",
    "Kromos Elevens",
    "Krovikan",
    "Krushdhead",
    "Krustenbrot",
    "Krystal Stylenger",
    "Krystof Albrecht",
    "Kulib&Shaman",
    "Kupewa",
    "kupo",
    "Kurt Ingersole",
    "Kurtis Ras",
    "KuruptedRedneck",
    "Kurzer183",
    "Kuschelchen",
    "KushrenadaT",
    "Kusko1810",
    "Kusuda_Aina",
    "Kwanglok Kim",
    "KwirkyJ",
    "Kwiss",
    "Kwuncha Lichuntsa",
    "KycKyc",
    "Kyle Hurlbert",
    "Kyle Larouche",
    "Kyle Willis",
    "KyluS.C",
    "Kyros, Devourer of Worlds",
    "Kyrylo Sobolyev",
    "Kyubey64",
    "L J Redman",
    "Laaknor",
    "LadonCaildir",
    "laemmi",
    "LaggyTim",
    "laige",
    "Lake Flynn",
    "Lalu4Ever",
    "Lamech",
    "LaniusFNV",
    "Lars Englert",
    "Lars Romeijn",
    "Lars The Devil",
    "Lars-Sebastian Larsen",
    "lastmikoi",
    "LateKnight",
    "Latham Burgess",
    "Laughing Viking",
    "Laurence Bolton",
    "Laurent Sauvé",
    "LAVANSEAU",
    "lazycurler",
    "lbmarshall",
    "LearnVisualStudio.NET",
    "Lee Dong gi",
    "Lee Hanner",
    "Leif",
    "Leightonne",
    "Lemming",
    "Lemur X",
    "Lenar Hoyt",
    "Lenni Zindrion Ström",
    "Lennia Flower",
    "Lennyroquai",
    "Leo",
    "Leo Potter",
    "Leon",
    "Leon Jeppesen",
    "Leon Pennington",
    "Leon Styles",
    "Leonardo Vaz",
    "Leopold Pöchinger (leschi1112)",
    "Leopold Serdet",
    "LeprechaunDown",
    "LeRoot",
    "lessthanthree",
    "Lethrington",
    "Leveller Bringer of Beer",
    "levi Burgers",
    "Lewek",
    "Lexon78",
    "Lexx1853",
    "Le_Flemard",
    "Lhama",
    "Liam Herrick",
    "Liam Wagstaff",
    "Lifell",
    "lightbender255",
    "LightPhoenix1242",
    "Lil Sweety",
    "Lilith Wroth",
    "lillefyr79",
    "lilmnm-kamikaze-",
    "liloso",
    "Lil_Azn_Dude",
    "Limco",
    "Link98723",
    "Linkin Simo",
    "Linkus",
    "Linus 'Vapid' Närkling",
    "Linuxjoe™",
    "Lippy",
    "Lishren",
    "Lisranda",
    "Lixbdennis",
    "Llama Rancher",
    "LLL3",
    "Locus Control",
    "LOFT",
    "Logan \"François\" Bleeker",
    "Logan Farrell",
    "Loki Glynn",
    "Lolpi",
    "Lonely Wolffe",
    "Lonelydude",
    "loom",
    "loot3r",
    "Lord Damen",
    "Lord Honk",
    "Lord Latimer",
    "Lord Oahnip",
    "Lord Raven Shadow",
    "Lord Rob",
    "Lord Romeo III",
    "Lordalex8888",
    "LordBane",
    "LordBucketron",
    "LordEddi",
    "LordJrPenguin",
    "LordOfTheTrains",
    "LordZugzwang",
    "Loren1350",
    "Lorenzo Reijndorp",
    "Loris Giuliani",
    "LotA the transport belt maniac",
    "Louis-Philippe 'xAt0mZ' Baron",
    "Louvet",
    "Lsathranil",
    "LT.killer",
    "LTL King",
    "Luaan",
    "Luc Everse",
    "Luc Marc Dijkstra",
    "Luca \"Mantula\" Manunta",
    "Lucanthreus",
    "Lucas \"Frakthal\" Moro",
    "Lucas Antonelli",
    "LucifersSeraph",
    "Luckcolors",
    "Ludsoe",
    "LuiB",
    "luimodo",
    "luiscity",
    "Luiz Guilherme Sato Franca",
    "Lukas \"Nic\" Gerstner",
    "Lukas Eugster",
    "Lukas Sutech Byrtus",
    "Lukasz Maslanka",
    "Luke Danes",
    "Luke Hermanson",
    "Luke Hoschke",
    "Luke Stephens360",
    "luke welsh",
    "Luke X Jespersen",
    "Lumatan",
    "Luminai",
    "Lumindia",
    "Lumos Ithin",
    "Lunafox",
    "lunapark",
    "Lunar",
    "Lunatrius",
    "Lundis",
    "Lurker's Rock",
    "Lurmey",
    "Luuk Lute",
    "Lyall Pearce",
    "LykoGod",
    "Lysator",
    "M. Boe Pedersen",
    "M. Hockenberry",
    "M.J.Edwards",
    "m4c0",
    "Maarten Bakker",
    "Maaslander",
    "Maatanen",
    "mabako",
    "MacenBacen",
    "Maciej Kulka",
    "Macintosh Still",
    "Macrixen",
    "Madara Uchiha",
    "MadZuri",
    "MagicJess",
    "Magnus Greiff",
    "Magnus J",
    "Magnus S",
    "Magos",
    "Maik Roseboom",
    "MaiKitty",
    "MajikMonkey",
    "MajorZeus",
    "Makar",
    "MaKeDoN",
    "makkaklaris",
    "MAKO",
    "MaksNovalis",
    "Malachi McDonald",
    "Malcolm Sleight",
    "Malcon",
    "Malediction",
    "Malorien Lelsarth",
    "Malte Gerner",
    "Malum",
    "Man In The Hat",
    "MANCHUCK",
    "Mangledpork",
    "Manters Godguard",
    "Manuel",
    "Manuel Baez",
    "Manuel Lara Bisch",
    "Manuel Merzinger",
    "Manuel Nagler",
    "Manuel Rauber",
    "Maracoolhit",
    "Maravalhas",
    "Marbin Drakon",
    "Marc 'CodeDude' Luther",
    "Marc Cahill",
    "Marc Chapman",
    "Marc Cookerly",
    "Marc Falabregues",
    "Marc Hannah",
    "Marc Jaisek",
    "Marc Schroth",
    "Marc Stampfli",
    "Marc Sumi",
    "Marc-André Gaudry",
    "Marcel Küpper",
    "Marcial",
    "Marco Goebel",
    "Marco Holzmayr",
    "Marconos",
    "Marcus Doyle",
    "Marcus Lynch",
    "Marcus Teubner",
    "Marek Rosa",
    "Marenthyu",
    "Marflag",
    "Marian Hälbig",
    "Marin Wyden Novels",
    "Mario Oberhollenzer",
    "Mario Stangl",
    "MarioneTTe",
    "Marius Talseth",
    "Mark \"Smash0r\" Muller",
    "Mark Craig",
    "Mark Hynes",
    "Mark Kerkdijk",
    "Mark Machine",
    "Mark Rathjen",
    "Mark Rebane",
    "mark rotermund",
    "Mark Spoerl",
    "Mark von Drake",
    "Markheloking",
    "Marko \"Koscum\" Vinu",
    "Markus \"Lupus\" P.",
    "Markus Lewandowski",
    "Markus Peitz",
    "Markus Scheuer",
    "Markus Sturn",
    "Marokar Blackwood",
    "marsman141",
    "Martc",
    "Martijn \"Winter\" Bekmann",
    "Martin Blue",
    "Martin Burton",
    "Martin Callesen",
    "Martin Eichner",
    "Martin Entlich",
    "Martin Hocking",
    "Martin Hrubý",
    "Martin Riis Nielsen",
    "Martin Steffen",
    "Maru Frozen",
    "Marvin Kirsch",
    "Marwin",
    "MaskedChaosky",
    "Mason Harrington",
    "mason pedersen",
    "Mason Roller",
    "Master Bagley",
    "Master Mallard",
    "MasterSJT",
    "MasterTaz",
    "Mathias Simonsson",
    "Mathias Stabell",
    "Mathieu Garstecki",
    "MatLaPatate, early tester",
    "Matrox[FX-1]",
    "Matt",
    "Matt \"Furious\" Freeman",
    "Matt 'LXKM' Shaw",
    "Matt D'Angeli",
    "Matt Day",
    "Matt Gorle",
    "Matt Hopper",
    "Matt Huggins",
    "Matt Raynor",
    "Matt Richards",
    "Matt Shannon",
    "Matt Siddle",
    "Matthew \"Fox\" Joiner",
    "Matthew A. Miller",
    "Matthew Awesome Daniels",
    "Matthew Colwell",
    "Matthew K. Crandall",
    "Matthew Lau",
    "Matthew Palmer",
    "Matthew Salinas",
    "Matthew Urke",
    "Matthew Wasserman",
    "Matthias Hampel",
    "Matthias Kuus",
    "Matthias Reissner",
    "Mattias \"Kleedix\" Olsson",
    "Mattias Lingh",
    "Matty Newland",
    "Mattyrogue",
    "Maudlin K. Beykhan",
    "Mauschi",
    "Max",
    "Max Declan Nokleberg",
    "Max Grant",
    "Max Kaneston",
    "Max Paul",
    "Max van Essen",
    "Maximilian Marx",
    "Maxwell Black",
    "Maxx Smid",
    "Maxx Wyndham",
    "mbritb",
    "MC Lenny D",
    "McModder",
    "McMoo_Twitch",
    "mcp95",
    "McPhisto2051",
    "MD Zoran",
    "Meakovic",
    "meatsack",
    "MegaBlindy",
    "MeinAccount",
    "Meinrad Stockinger",
    "Melfish",
    "Melowin",
    "Meme Media Lab.",
    "Meph",
    "Meradz",
    "MercFHire",
    "Mercury044",
    "Merelleya",
    "Merle Haggard",
    "Meserion",
    "Metehan Kaplan",
    "Metnavman",
    "Metodius Skorpa",
    "Mezilsa",
    "Mia",
    "Michael \"Mardu\" Glatz",
    "Michael Barnes II",
    "Michael Christopher",
    "Michael Derksen",
    "Michael Fairchild",
    "Michael Feltmann Nelander",
    "Michael Harris",
    "Michael Hole",
    "Michael Holland",
    "Michael Jones",
    "Michael Ko",
    "Michael M.",
    "Michael Nadeau",
    "Michael O'Harra",
    "Michael Ofner",
    "Michael Phelan",
    "Michael Stadel",
    "Michael Verhülsdonk",
    "Michael Wallace",
    "michaelb958",
    "Michal Raab",
    "Michel Schaitl",
    "Michiel Knol",
    "Microbe2070",
    "MicroSteve",
    "MidnightMurderer",
    "MightyMike",
    "Mikael - RealZelyet",
    "Mikael Kassell",
    "Mikael Kiviharju",
    "Mike Atamanchuk",
    "Mike Jones",
    "Mike Strehlau",
    "Mike Takumi",
    "mike77tmc",
    "MiKeael Road",
    "Mikedu900",
    "Mikhail Balyuk",
    "MIkhail Kyshtymov",
    "mikmatt1998",
    "Mikrotherion",
    "mikuli",
    "MilkJugg24",
    "milleniumbug",
    "Milvus milvus",
    "Mind",
    "Mine Tech Industries",
    "Ming",
    "MiniMeOSc",
    "Minimitch",
    "Miracoulon",
    "Mishima Hiragama",
    "MISO-SHIRU-MG42",
    "Mister JOJO",
    "Mitchell Frondal",
    "Mitchell Grenier",
    "Miturion",
    "Miyu Aria",
    "MJ Langelier",
    "Mjir",
    "ml0130",
    "mngrif",
    "mobbsy91",
    "Modest Zlatolobov",
    "Modiseus",
    "Moholmarn",
    "Molay",
    "Molgro999",
    "Mom look what i did - Alex",
    "Monaray",
    "Money Longnose",
    "MonkeyNutz",
    "Monofuel",
    "MONOmah_V",
    "Montoyo",
    "Moo",
    "moody01",
    "Moondrixx",
    "Moonfisk",
    "Moonscar",
    "Moonstone",
    "Morbulus der Kranke",
    "Morgano",
    "Morgoth",
    "Moritz Schmid",
    "Morotstomten",
    "Moroyoshi",
    "MorpheusXAUT",
    "Morten Jespersen",
    "Mortiglea",
    "Mougugy",
    "mpease",
    "Mpmpmpmp",
    "Mr BeAsT",
    "Mr Eguia",
    "Mr EpiX",
    "Mr Green",
    "Mr Lugg",
    "Mr Lundh Sweden",
    "Mr. Burd :V",
    "Mr. Foken",
    "Mr. Muffin Time",
    "Mr. N. Mukkas",
    "Mr.Dropin",
    "MrGaminger",
    "MrGamma195",
    "MrKMG",
    "MrMakeIt",
    "mrphlick",
    "MrPippali",
    "MrSwedishFish",
    "MrTimmato",
    "MT Home Technology",
    "Muardin",
    "Muse Flare",
    "Mute Kun",
    "MuteGiggling",
    "MWJJB",
    "MWMalcolm",
    "Mypenter",
    "Mysteria",
    "Mysticalpchan",
    "Mytrandir",
    "N. N. Westensee",
    "N00byEdge",
    "N83DW4RD5",
    "NaabCorum",
    "Nabla",
    "Nadine A. and Julien M. (GER)",
    "Naelain",
    "naervig",
    "NaevaKitty",
    "Nai",
    "Nai'Elak",
    "Namel909",
    "Nameo0",
    "Nanonium",
    "Nantang'Itan",
    "Napier",
    "Narc",
    "Nardix",
    "Nash",
    "Nat",
    "Natalia Wydra",
    "Natalie",
    "Nate Alchesky",
    "Nate67660",
    "NateMercer",
    "Nathan",
    "Nathan \"Nephilim\" Padilla",
    "Nathan A. Haugh",
    "Nathan Hammond",
    "Nathan Lewis",
    "NatoMadi",
    "Naugles",
    "Nazrael",
    "Naztor",
    "NdWar",
    "NecoAngelus",
    "Necrogami",
    "Necromechanic",
    "necronicone",
    "Ned Geake",
    "Neil Pring",
    "Neko-Shana",
    "Nemisus",
    "Nemmie Smulan",
    "Nemo",
    "neo1mmatrix",
    "neofis",
    "Nesflaten",
    "Neuroloops",
    "NexAngelus7703",
    "Nexii Malthus",
    "nextized",
    "Nezaris",
    "Nguyen Hoang Duc",
    "Nicholas Kimball",
    "Nicholas Marshall",
    "Nicholas Winters",
    "Nick \"smudj\" Robson",
    "Nick Donnelly",
    "Nick Geoffroy",
    "Nick McCracken",
    "Nick Morrell",
    "Nick Pannuto",
    "Nick Stubblefield",
    "Nick Zelinski",
    "Nicko Böhnke",
    "Nico Edler",
    "Nicolai Solving",
    "Nicolas Beaussart",
    "Nicolas Briand-Mercier",
    "Nicolas the Hamstroll",
    "Niels de Roo",
    "Nigel Goodman",
    "NightFire Navy[NINA]",
    "NightfireZero0",
    "Nightwind Lorr",
    "Nightwolfy13",
    "Nihilivin",
    "nike_dj1",
    "NikiPiano",
    "Nikita \"LordXaosa\"",
    "Niklas Buck",
    "Nikolai Kabuth",
    "Nikolai Neff",
    "Nikolas Penney",
    "Nikolas Salcedo",
    "Nilixen",
    "Nils",
    "Nils Meyerhoff",
    "NineStitches",
    "Ninja 5tyl3",
    "Nion",
    "Nippiee Dannen",
    "Nirahiel",
    "Nishiki",
    "Nishnat Ranjan Mishra",
    "Nithanim",
    "Nivram",
    "Noah Ergezinger",
    "Nobody#Cares",
    "Nobodytoyou",
    "nobukatsu",
    "Noisyboy",
    "NomadFool",
    "NomanDAX",
    "nomathplz",
    "Nomenclate",
    "Noob Tenschi",
    "Noodles",
    "Norman Landsberg",
    "Northern Performance",
    "Norville Rogers",
    "Nosave",
    "nostromer",
    "Nosyt",
    "Notaßot",
    "notdsk",
    "notmyname",
    "nove",
    "Novemburr",
    "NoyzMaker",
    "Noé Maillard",
    "Nukewarhead",
    "nullv",
    "Nuno Alves",
    "Nuppzi Let's Play",
    "Nutmonkey",
    "NYC Resistor",
    "Nymark",
    "Nyx Erlone",
    "O. Morten Sørlie",
    "o4kapuk",
    "ObamaCare",
    "Obedience",
    "Oblivion",
    "OctarineNoise",
    "Octavia Melody",
    "octo",
    "Oelbaron",
    "Ofio",
    "Okilubb",
    "Oktabyte",
    "Old Crow Express",
    "OldBull78",
    "OliHar",
    "Oliver Kahrmann",
    "Oliver Koch",
    "Oliver_Defusco",
    "Olmmy",
    "Omega",
    "OmegaRogue",
    "Omicronus",
    "OMNI GORD",
    "Omni Industria Megacorp",
    "Omnichron9",
    "Onebadterran",
    "OneViking by The Art of Warfare",
    "or this mystery box(pick one)",
    "Orhan 'aib' Kavrakoglu",
    "Originus",
    "oritkan",
    "Orson Westberg",
    "Oscar Pettersson",
    "Oscskinski",
    "Osiris",
    "Osuyuushi",
    "oswald jarick",
    "Ovaron",
    "Oveerlord92",
    "OvenAut",
    "overload",
    "Overloaded_Wolf",
    "Overlordraz",
    "Owen Fitzpatrick",
    "Oxidenetwork Rocks!!!",
    "Oxlamon TwoRat",
    "OzHawkeye",
    "Ozymandias",
    "pabelanger",
    "Paintdev",
    "PalverZ",
    "Panda556766",
    "Pandarenkuma",
    "Panick_II",
    "Panu Sutela",
    "Papa Elch",
    "Papa X",
    "ParadoxV",
    "Paranoia",
    "Pascal Rüther",
    "Patchi",
    "Patofet",
    "Patric20878",
    "Patrick Eichelberg",
    "Patrick Kelly (Nazasu)",
    "Patrick van der Leer",
    "Patrick vd K",
    "Patrick Xia",
    "Patrick Zameter",
    "Patrik Bjorkenheim",
    "Pauk666",
    "Paul 'Xanzibaarbarian' Cooper",
    "Paul Barth",
    "Paul Haller",
    "Paul Munro",
    "Paul Peters",
    "Paul Sachse",
    "Paulo Lopes de Carvalho",
    "pauloalberto",
    "Pavel Bystrov",
    "PDemon",
    "PDX Payback",
    "Pedro 'CloneWarrior85' Antunes",
    "peer",
    "Pekka Kinnunen",
    "Peltier Gregoire",
    "Penguin_Poker",
    "Pentorin",
    "Pepperpeps",
    "Permarin1",
    "Pestery",
    "Pete O'Leary",
    "Peter Ahlstrom",
    "Peter Friese",
    "Peter Kaszynski",
    "Peter MacMillan",
    "Peter Major",
    "Peter Vetterli",
    "Peter Wyroba",
    "Peter_v_Gruen",
    "Petr Minařík",
    "Petraea",
    "Phantomix",
    "PhantomMadness",
    "Phidi",
    "Philip Ettl",
    "Philip Hansen",
    "Philipp Schiess",
    "Philippe Dellaert",
    "Phillip \"Valgarian\" Vertner",
    "Phillip Brunyee",
    "Phillip James",
    "Phillip M. Vector",
    "Phillip Rohde",
    "Phillip Vossler",
    "Phillyduck",
    "Phlegyas",
    "Phosphorescent",
    "Phyire",
    "Phyn",
    "Piermur",
    "Pierre Gufler",
    "Pierre Mura",
    "Pierre-Étienne Chassé",
    "Piggy",
    "PiggyWhiskey",
    "Pikman46",
    "Pilon866",
    "Pingel",
    "Pink Husky",
    "Piro_Maniak",
    "Piton",
    "PixelPrime",
    "Pixiecrap",
    "Pjar Normand",
    "PJH",
    "Pjokkemon",
    "Planstr",
    "Plebs be upon you",
    "Pneumono",
    "PnLarsson",
    "Polo Juice",
    "PolygonAssassin",
    "Pontus Engberg",
    "poorprogramming",
    "Porch Iges",
    "prak",
    "Preizhour",
    "Priestress",
    "Promethean",
    "Proq",
    "protoss",
    "Pruvan",
    "psihius",
    "Psirrow Anei",
    "Pskovhansen",
    "PsychoTRS",
    "Ptilait",
    "Puggy",
    "PuppetMuncher",
    "Puritan74",
    "Purple Haired Geek",
    "Purplenavi",
    "Putimir Vladin",
    "Pyrodogg",
    "Python Ambassador of Serbia",
    "Pøklz",
    "Qbe",
    "Quentin Noël",
    "Quentin Satelmayer",
    "Quinlan",
    "Quis",
    "quok",
    "R.C Halsvik",
    "R3CONN3R",
    "Raasil",
    "RabidRapidRabbit",
    "RadioMania",
    "Rafael C. Biasi",
    "Rage",
    "Rahjital",
    "Rallias",
    "RalphFox Nitriex",
    "Ram",
    "Ramba Zamba",
    "Ramon",
    "Random-Roastbeef",
    "RandomEngy",
    "randomspawn42",
    "Ranick",
    "Rashael",
    "Raspvtin",
    "Rasta",
    "Rathios",
    "Ratzfaz",
    "Rautert",
    "RavenHexx",
    "Ravior Metal",
    "Ravix V. Poulsen",
    "Rayackvor",
    "RaZim",
    "Rbit",
    "RCcola1987",
    "ReahtLegionnaire",
    "ReaperIndustries",
    "ReapXsnipeS",
    "Rebellionmerc",
    "red dutton",
    "Reddy Fox Moon",
    "redhondachic",
    "RedneckHijacker",
    "RedPawn",
    "redragon309",
    "Redshadow",
    "Redzombi",
    "Reece Shaw",
    "reenigne",
    "regis",
    "ReIco",
    "ReliteTheFires",
    "Remasgnal",
    "Remko de Bruin",
    "Remulis Scarlet",
    "Remwald Librod",
    "Rene S.",
    "ReneMuetti",
    "Rens2Sea",
    "Rensiur",
    "Renwallz",
    "Renzo van Rhijn",
    "Rescla",
    "Resident_Rhodan",
    "RETARDEDHAIR",
    "RetiredNavyVet",
    "Reububble",
    "Revan Leuverman",
    "Rex2432",
    "Reygan",
    "Reyu Zenfold",
    "Rhaktar",
    "Rhea the Godkitty",
    "Rhodan",
    "Rhory Bader",
    "Rhys Neilson",
    "Ricardo",
    "Rich Pereira",
    "Richard Abbott",
    "Richard Aldous",
    "Richard Darrington",
    "Richard Gauthier",
    "Ricky Burtrand",
    "Rico John",
    "Rijzwijk Mostardos",
    "Rik van der Aart",
    "Rikard Hjelmgren",
    "Rikkavidu",
    "Riley",
    "Rinaldo Boeje",
    "RipGeneraL",
    "Rippey",
    "Risingfate",
    "RitonLaBevue",
    "Rizzla Blue",
    "Rizzok",
    "rjek",
    "rk84",
    "Rndsum BOT",
    "Ro.Fl. e.V.",
    "RoastedJohnson",
    "Rob Audenaerde",
    "Rob Schutt",
    "Rob W Jacob",
    "Robert \"Bullet25\" Kauffman",
    "Robert Bülow",
    "Robert Conner",
    "Robert Fey",
    "Robert Fitch",
    "Robert Hanson",
    "Robert Hunt",
    "Robert Janes",
    "Robert Martinez",
    "Robert Miething",
    "Robert Nilsen",
    "Robert R. Russell",
    "Robert William Lightfoot",
    "Roberta Peddle",
    "Roberto Tamagnoli",
    "Robin Rogge",
    "RoboRocket",
    "Robot Joe",
    "RobotSpider",
    "Rochie",
    "Rockstaricp420",
    "Roger Vela",
    "Rohadnis",
    "Roland ten Napel",
    "Roman Lendel",
    "Roman R. Hanisch",
    "Ronni Magnusson",
    "ronny",
    "Ronny Fagerlund",
    "Roope Pihlaja",
    "roqs",
    "Rorbie",
    "Rory D Lynch",
    "Rory Wise",
    "rosedk",
    "Ross Ramsay",
    "Rotato Industries",
    "Rowan Switzer",
    "rR Leviix",
    "Rrokan",
    "RTFM",
    "Ru$$ Money",
    "Ruangor",
    "Rubilon",
    "Ruby Shnee née Rose",
    "Rudolf das kleine Rehntier",
    "Rufert",
    "Ruggèro",
    "Rumbum (CPlasters)",
    "RushRaccoon",
    "Ruskels",
    "Russton Smith",
    "Rusty the Wolf",
    "Ryan",
    "Ryan Bates",
    "Ryan Clark",
    "Ryan Groth",
    "Ryan Parker*",
    "Ryan Shadbolt",
    "Ryan W Sims",
    "Ryzoloki",
    "s33r",
    "s5Zang Wo0t",
    "Sabaka",
    "SabbaGandalf",
    "Sable Drake",
    "sagerus optimus",
    "Sagramor de Zyn",
    "saladin",
    "Salorar",
    "Salorium",
    "Sam \"Stingray\" Dover",
    "Sam Biddell",
    "Sam Courtney",
    "Sam Reeves",
    "Sam Spurrell",
    "Sam Uebersax",
    "SameOldEarl",
    "Sami Nieminen",
    "Sammich Inman",
    "SammyScar18",
    "Samnixpc",
    "Sampwnage",
    "Samuel Gonzalez Martínez",
    "Samuel H Brown",
    "Samuel Kelly",
    "Samuel Pembroke",
    "Samuel William Smart",
    "SanderScamper",
    "Sandro Salvati",
    "Sangrifeld",
    "SanityCat",
    "Sansimir",
    "Sapphire Crook",
    "Sapphire Hema",
    "Sarah Natalia",
    "Sarge852",
    "Sariondil",
    "Saron Grave",
    "Sarunas \"Duke_Eradication\" Misevicius",
    "Sascha Debney Matiszik",
    "Sascha van der Schoot",
    "Saskia B Hansen",
    "Satan",
    "Satis",
    "Savotage",
    "Sberdila",
    "Scaleneash89",
    "Scalio",
    "Scandinator",
    "Scarhoof",
    "Scarper",
    "Schatti",
    "Schrauffi",
    "Schreck84",
    "Schwapp",
    "Schwiizer",
    "ScoobTheNoob",
    "Scorge",
    "Scorsey",
    "Scott Austin",
    "Scott Broadbent",
    "Scott Frazer",
    "Scott John Beal",
    "Scott Killen",
    "Scott Lanning",
    "Scott Regan",
    "Scott Schwerdfeger",
    "Scruffy Batface",
    "Seaglobe",
    "Seamus O'Boyle",
    "Sean M. Chase",
    "Sean Mire",
    "Sean Sands",
    "Seanica",
    "Searge",
    "Sebastian Audet",
    "Sebastian Barbes Seyfarth",
    "Sebastian Lange",
    "Sebastian Nilsson",
    "Sebastian Schneider",
    "Sebastian Topp",
    "Sebastian van Rhijn",
    "sebson",
    "Seedykoi",
    "Sekkmer",
    "Seldar",
    "Seluj78",
    "Semion Nadezhdin",
    "Semoset",
    "Seraphins",
    "Serdar Akkilic",
    "Serge",
    "Serge Fallmann (SilverFolfy)",
    "Seth Burrell",
    "Seth Sneddon",
    "Seth Tierney",
    "Seth Toles",
    "Sevadus",
    "sfxworks",
    "Sgtazza",
    "Shackles",
    "Shade4390",
    "Shadow",
    "Shadow",
    "Shadow Guardian 507",
    "Shadowofadoubt",
    "ShadowWalkerA",
    "ShaiTan",
    "Shane Johnstone",
    "Shane Watson",
    "shanegss",
    "Shannon Gorski",
    "Shannon koger",
    "Shantics",
    "SharkWipf",
    "sharky11987",
    "Shawn 'Vhargon' Norton",
    "Shawn Brown",
    "Shawn Conrad",
    "Shawn Pearson",
    "Shaxnon",
    "Shayne Stewart",
    "shenryyr",
    "Shentienlung",
    "Shibing Huang",
    "Shikama",
    "Shimool",
    "ShinBoneZ",
    "Shiro",
    "Shiro The Kitten",
    "ShirowShadow",
    "Shoghi Cervantes",
    "Sholla",
    "Shoopin",
    "Shosh",
    "Shtong",
    "Shuzumi",
    "Shylo132",
    "Side A.",
    "Sidola",
    "Siegfried W. Kettlitz",
    "Siggy",
    "Sigillus",
    "Sigmund Bautista",
    "SilenceStands",
    "SilentEcho1181",
    "Silentsouls",
    "Silver Dusk",
    "SilverBeard",
    "Simon (Nemos) Eriksson",
    "Simon Crawley",
    "Simon Stadelmann",
    "Simon Wheatcroft",
    "Simondf1",
    "Singh Saab",
    "Sinnersaix",
    "Sinrise",
    "Sir Frank Henrik",
    "Sir Nicholas J. Vetterli",
    "SirArag",
    "Sirbloodking",
    "SirBlubbalot",
    "SirOtterlot",
    "SirRuc",
    "SirSmuggler",
    "Sir^Ducer",
    "Sisaroth",
    "Sivert Henriksveen",
    "sixkiller5",
    "Siôn 'Ifrit' Morgan",
    "Sjors Schiebergen",
    "skanx",
    "SkaveRat",
    "Skellious",
    "skintkingle",
    "skoolerror",
    "SkorpTec",
    "Skylordgadget",
    "Skywishes",
    "Slade117",
    "SlaveofPeon",
    "sleepyboi89",
    "Slim Fandango",
    "Slinger Jawson",
    "SmallDisturbedChild",
    "Smallrolf",
    "Smarty",
    "SmashinVideoPlayer",
    "Smelborp Squared",
    "Smoovious Laxness",
    "SMS Park",
    "Sneakyperson",
    "Snorre Alvsvåg",
    "Snowman's Mind",
    "Snuggly Wuggums",
    "Sockrates",
    "Soda5261",
    "sodhunter",
    "Sofox",
    "Solene & Jeff",
    "Solkongen",
    "SombreLune",
    "Sondergleich",
    "Sora Hjort",
    "Soren Reber",
    "Soud Alobaid",
    "Souless Raven",
    "Soulrest1921",
    "Sound_of_Drums",
    "Sour.Sun",
    "Sp8ter",
    "Space Egg",
    "SpaceCabbie",
    "spacemanguy",
    "Spans",
    "Sparky",
    "SpartanVader",
    "Spazza360",
    "SpectralGuardian",
    "SpeedDaemon",
    "Speedy24",
    "speedy45",
    "Speiderful",
    "Speidy674",
    "Spielmann",
    "spikedoom08",
    "spikefire",
    "Spladex",
    "SplittingMnut",
    "Spokig",
    "Sponsored by Tamtooe [Wroclove]",
    "SPOON 1982",
    "Sporling",
    "spynet1966",
    "SQiRL",
    "SquaredCubed",
    "SrMike",
    "St3in3r",
    "Stan O",
    "StanFear",
    "Starchie",
    "stardestroyer12",
    "Starholme",
    "StarPowered",
    "StarRider OutPost",
    "Starry Night",
    "StarRyder",
    "starslayer",
    "Starwin",
    "Stebbbi",
    "Stefan Bosch",
    "Stefan Braun",
    "Stefan Gaertig",
    "Stefan Kent",
    "Stefan Ladage",
    "Stefan Möhl",
    "Stefan Sing",
    "Stefan van den Berg",
    "Steffen Reinhardt",
    "Steinar",
    "StellerWorks",
    "Stephan and Kiki Hug",
    "stephan evers",
    "Stephan Kandels",
    "Stephan Reiter-Петров",
    "Stephen Collins",
    "Stephen Rush",
    "Steve Maksimovic",
    "Steve Wagner",
    "Steve Wilson",
    "Steven Marks",
    "Steven Noonan",
    "Steven Perry",
    "Steven R Britton",
    "Steven Surowiec",
    "steveyg101",
    "SteyrCVT170",
    "Stijn Timmermans",
    "StimSim",
    "Stivoxius Prime",
    "StonedOne",
    "Storm The Dog",
    "StormKern",
    "StrangeW",
    "StrayMav",
    "Strend0Rama",
    "Striker2379",
    "Stront1us",
    "Stryder1988",
    "Strzelec",
    "Stuart Bunn",
    "Stute",
    "Sukasa",
    "Sullivans (Justin Schrader)",
    "Super Sips_ Fan 3 Million",
    "Supercheese",
    "Superlordpedro",
    "SuperTerrador",
    "Suppekaj",
    "SupperCraft5000",
    "SuppleZombieKitten",
    "Suppressor153",
    "Suranis",
    "Susua",
    "Sutoraika",
    "Svein Hofseth",
    "Sven 2SRonin",
    "Sven Bischoff",
    "Sven Stuebler",
    "Sven van den Akker",
    "swaggah2daD",
    "Swaglag",
    "Swamy",
    "Sweet Cheeks the Youtuber",
    "Sweistergeist",
    "Swen K.",
    "Swervy Ninja",
    "Swiss",
    "Sydney Holland",
    "Sylias",
    "Sylvian Munier",
    "Synliss",
    "SyoyoFR",
    "Szereka",
    "Tabaxi",
    "Tabisama",
    "Tad Williams",
    "Taehupo",
    "Tahsin K",
    "Taimyr Zann",
    "Takshaka",
    "Taliki",
    "Tallest of Treas",
    "Tama1618",
    "Tanlorik",
    "Tanuberos101",
    "TaonasSagara",
    "Taorakis",
    "Tap & Splat",
    "Tardan",
    "Tashdacat",
    "Tathra",
    "Tatsuya Saito",
    "Tavis McLean",
    "Taw",
    "Taxoz",
    "Tayler-Tech Industries",
    "Tazoo",
    "Tazzer93",
    "Tbolt2025",
    "TeamFantiX",
    "Tech1337",
    "Tech_GamingTV",
    "Tedessence",
    "Teebor",
    "Tegual",
    "tehcrash",
    "TehRoach",
    "Teme",
    "Temterator",
    "Tenandra",
    "Tenebrous",
    "Tenjina",
    "Teodor Norén",
    "Teodor Vecerdi",
    "Tepictoc",
    "tequilachef0815",
    "Tercicatrix",
    "Terra_Incognito",
    "Terry",
    "Terry R Meilleur",
    "TeslaAiracomet",
    "TestSquadron-TypeO",
    "Thamal",
    "Thanassos",
    "Thasher",
    "ThatRedEngineer",
    "Thaui",
    "thayne womack",
    "ThayTheWolf",
    "The AlCaTrAzz",
    "The DiClaudio Family",
    "The Doctor",
    "The Doofmeister",
    "The Dutchess Nicole",
    "The Empire",
    "THE EVA SERIES",
    "The Fox Council",
    "The Great Wyrm",
    "The Grunge",
    "the Incredible Nothing",
    "The Invisible Man",
    "The Lapis Fox",
    "The Mighty Spoon",
    "the Monster Raving Loony Party",
    "the Necronomiconomist",
    "The Phoenixian",
    "The Technomancer",
    "thebad300",
    "TheBigBlah",
    "TheCraftyDawg",
    "TheCyborg",
    "thedarknightam",
    "TheDonAbriano",
    "TheDoubleDPlayer",
    "Theendlessdrumming",
    "thefox963",
    "theglasskat",
    "TheGlassman333",
    "TheGoldenBrotherhood",
    "TheGoldJoker",
    "TheGreenkey",
    "TheHunt0r",
    "TheInker",
    "TheKeyn",
    "TheLeftPinky",
    "TheMotherTroll",
    "TheMrDarkrider",
    "TheNimbleNinja",
    "Thenorups",
    "TheOperator io",
    "theo_the_ape",
    "Theraleo",
    "TheStuffz",
    "TheTacoRancher",
    "TheTerraner",
    "Theudeux",
    "TheWarheadLP",
    "Thijs Vogel",
    "Things",
    "ThinkTwice",
    "this isn't real wake up",
    "Tholton",
    "Thomas",
    "Thomas \"Zaydon\" Lust",
    "Thomas \"Squall\" Léturgie",
    "Thomas A.",
    "Thomas Batenburg",
    "Thomas Blion",
    "Thomas Coller",
    "Thomas Greer",
    "Thomas Krieger",
    "Thomas Lembrechts",
    "Thomas Lund",
    "Thomas Olvitt",
    "Thomas RedGrave",
    "Thomas Rowan III",
    "Thomas Woods",
    "Thore E. Engel",
    "Thorgeir Marthinussen",
    "Thorkild A. Andersen [Multivers]",
    "Thorsten Stanitzok",
    "Thr3d",
    "ThreeSevenths",
    "Thudjy",
    "Thunder",
    "Tiago Barroso",
    "Tibsfox",
    "Tidos",
    "Tiffany Bennett",
    "Tigel172",
    "Tigerfly",
    "Tijn \"Juwelier KappaKnoef\" Priem",
    "Tilo Becker aka EviloKnievel",
    "Tim \"TTH\" Hopkins",
    "Tim Bain",
    "Tim I Hely",
    "Tim Showalter",
    "Tim Tupas",
    "Tim-Oliver Wagner",
    "timewarp",
    "Timmy1e",
    "TimoPlaysHD",
    "Timothy \"PTC\" Carol",
    "Timothy Elder",
    "Timothy Langley",
    "Timur S. Demiral (Bigdeathy)",
    "TiNgLe",
    "Tinilmabard",
    "Tiny Taco Team on Github",
    "Tivec",
    "Tizian Grub",
    "Tiz_MSE",
    "TJ 'Myrathi' Houston",
    "TKuja1",
    "tlcoffee",
    "Tleilandrek",
    "TLPineapple",
    "Toawa",
    "Tobias Bliksrud",
    "Tobias Franke",
    "Tobias G. Möh. [DKC-CP] BassDominator",
    "Tobias Löfling",
    "Tobias Milde",
    "TodesKiowa",
    "Togis",
    "Tokarea",
    "Tolana",
    "Tom",
    "Tom Atterbury",
    "Tom Browne",
    "Tom Burns",
    "Tom Ficcadenti",
    "Tom Hartnett",
    "Tom Irenicus",
    "Tom Pouthier",
    "Tom Rochette",
    "Tom Schuster",
    "Tom Slingi",
    "Tom Smotherman",
    "Tomas Roll Krognes",
    "Tomek31",
    "tomfrombaxter",
    "TomHasDen",
    "Tomik",
    "Tomo Ferega",
    "tomudding",
    "Tony Tallierchio",
    "TonyTyrax",
    "TonZa Terrawyng",
    "Topperfalkon",
    "TorKger",
    "Tortila",
    "Torven the grey",
    "Tosa",
    "Touya Akira",
    "toydarian",
    "Trangar",
    "Travis Christian",
    "Travis Overcash",
    "Trax Beaumont",
    "TRCrata",
    "Trees",
    "TreeTree, Reno Aerts",
    "Trevor Cooper",
    "Trevor Railman Fenlon",
    "Trevor Rose",
    "Trey",
    "TrihXeen",
    "trinistry",
    "TripleIndie",
    "Triska",
    "Tristan Hehnen",
    "Tro",
    "Troglodyte Games",
    "Trojan Ender",
    "Troy Gillis",
    "troy2k",
    "tsw",
    "Tubsy",
    "Tucker Brisson",
    "TuffyLovesFactorio",
    "Tunder_600",
    "Tuomas Paavola",
    "Turvelo",
    "Tusou.Game",
    "Tut",
    "Twilight Sparkle",
    "TwinkleFairy",
    "Twisted Code",
    "TwistedSeven",
    "Twistedt",
    "TwixMan83",
    "Twizted Sizter",
    "Tyler B.",
    "Tyler Boydston",
    "Tyler Cark",
    "Tyler Hoyt",
    "Tyler Hummel",
    "Tyler Lee",
    "Tyler Woodside",
    "Typhoonator",
    "Tyrin T.",
    "TysonsWorldOfGames",
    "Uberhenrik",
    "uditaren",
    "Udo Schmidt",
    "Udwin",
    "UenoStation",
    "UFeindschiff",
    "UFO Cat",
    "Ugruymiy",
    "umbrela347",
    "Uncle Ben",
    "Uncle Squish",
    "Unequity",
    "unflyable",
    "UniQcorN",
    "UnsanityLIVE",
    "Unsnarled",
    "Ununoctium",
    "UrbanWulf",
    "Ururun",
    "Utter Creativity",
    "UVDanger",
    "v12aml",
    "V1K1NG",
    "V453000",
    "Valdrake",
    "ValiZockt",
    "Vampiric Dust",
    "Vanderlof",
    "Vannflyhite",
    "Varchronus",
    "Varka",
    "vastoslorde",
    "Veaynon",
    "Vegeta897",
    "Veixus",
    "Veliox",
    "Vendias",
    "Verbina29",
    "Verdiumm",
    "Verenja Dane",
    "Verified by Verified",
    "Verir Ryu",
    "Vernus",
    "Vesaria",
    "Vianessa Hampson",
    "Victor Bondaruk",
    "Victor Dreygo",
    "Victor Fernandez",
    "Victor Tombs",
    "Vijay Holtkamp",
    "Viktor Očakovský / KillKillABC",
    "Viliam Manka",
    "Villatoro",
    "Vim Razz",
    "Vincent Wettig",
    "Vinicius Meireles",
    "Vinny Brim",
    "Violine",
    "visionfear",
    "Vivien Cassar",
    "Vladislav Isenbaev",
    "Vlastimil ''Wotis'' Šrek",
    "vlczero",
    "Volker K.",
    "Vora of FJ",
    "Vuemaster2",
    "Vulk la forge",
    "VUTechni",
    "Vvaridus Veridian",
    "Vymsz",
    "vzyBilly",
    "VánZán",
    "Vít Brunner",
    "Wacka",
    "Wade Tregaskis",
    "Wagner",
    "Wagner",
    "Waldy Angeloak",
    "Walter Paschal",
    "WangCoffin",
    "Warik Yacent",
    "WarMadMax",
    "wastrel",
    "Watatsumi",
    "WaTo",
    "Watty",
    "Wazuki",
    "Wazzebu",
    "WBrzosto_Pulawy",
    "WDDN",
    "WebHout",
    "Ween",
    "welshtony1",
    "Wermatswil",
    "Wes Oldenbeuving",
    "West.",
    "Westenberger",
    "Whiro",
    "Whiteluigi",
    "WhiteTigerLee",
    "Wickster83",
    "Wieprzu",
    "Wif Wiffles",
    "WildWolf",
    "Wilhelm Kristensen",
    "Will Baker",
    "Will forney",
    "Will Frost",
    "Will W Redeemer",
    "Willarun",
    "William",
    "William Grimm",
    "William H. Jones",
    "William Langdon",
    "William Rudenmalm",
    "William Wilson",
    "William Winston",
    "William Woelk",
    "Williston",
    "WillySpoon",
    "Windes*Fr",
    "WindPower",
    "Winnetou",
    "Wizzle0331",
    "Wolfbite",
    "Wolfchild",
    "Wolfgang Pastl",
    "Wolfie12",
    "WolfKnight",
    "Womble",
    "Wonky Phsicks",
    "Wouter Minten",
    "Wołodia",
    "Wratheous",
    "wrtlprnft",
    "Wubbel4",
    "WUDCHUCK",
    "Wutklumpen",
    "Wyatt Rawson",
    "Wyrik",
    "XANA520",
    "XarsYs",
    "Xawirses",
    "Xboy_SupCom",
    "xcran",
    "Xech",
    "xedre",
    "XelHaku",
    "Xemu",
    "Xenia Renner",
    "XeroR BattleR",
    "Xeteth",
    "Ximias",
    "xnmo",
    "Xolgrimm",
    "XscorpiontankX",
    "xskander",
    "xterminal86",
    "xXOptic_RugXx",
    "Yah Boi Lucas Alvarez",
    "YAKITORI",
    "Yamakiroshi",
    "Yammo Yammamoto",
    "Yankee Teacup",
    "yatti",
    "Yawen Song",
    "Yee Lee",
    "Yge Venema",
    "yobias hennings",
    "yoizukiyo",
    "Yooslis",
    "Yordi Geurts Yensequra",
    "Youtuber TheTrexable",
    "Yoyogre",
    "yqt1001",
    "Yttrium",
    "Yukitsu Times",
    "Yuof",
    "Yurily",
    "Yutakabareru",
    "Yvonne",
    "Z-Baby",
    "Zaas",
    "Zac \"Holladiewal\" Smith",
    "Zac Brown (NIKOtheMONKEY)",
    "Zach luc Picard",
    "Zach Noah",
    "Zach Triplett",
    "Zachary Banta",
    "Zachary Cathcart",
    "Zachary Mildrum",
    "Zachlightsabe",
    "Zack Z",
    "zaery",
    "Zakul",
    "ZanDak",
    "Zander Horn",
    "Zardath",
    "zarevak",
    "Zarkal",
    "Zasifras",
    "Zatrac",
    "ZavuX",
    "Zaxaramas",
    "ZayneGG",
    "ze.d",
    "ZeCaS",
    "Zecpan",
    "Zediatus",
    "zegurasu",
    "Zeiberschot",
    "Zemalf",
    "Zenblast",
    "Zengrath",
    "Zenimer",
    "Zenoah Direblood",
    "Zero Tachikoma",
    "Zero Valintine",
    "Zeth Kerman",
    "Zetter",
    "ZeusC2",
    "Zhinjio",
    "zidic",
    "Zidonuke Marshdevil",
    "Zigerot",
    "ziggleh",
    "Zisteau",
    "Zistil",
    "zivyTerc",
    "Zlosynus",
    "Zmegolaz",
    "Zobota",
    "Zoidberg",
    "zollman123321",
    "Zombielord Ativan",
    "Zombull",
    "zonthori",
    "ZOP",
    "ZornGottes",
    "Zortoch",
    "ZpixThaTurtle",
    "Zxypher",
    "zyxep",
    "[FR]LdtSten",
    "Ångström Trilobite",
    "Øyvind Heggstad",
    "사과맛TV (TV_Apple)",
    "좐털맨",
}
return backers