require "system.fluidflow"
require "system.saveload"
require "system.endpoint"
require "system.road"

local csystem = require "register.csystem"

csystem "generator"
csystem "powergrid"
csystem "fluid"
csystem "assembling"
csystem "chimney"
csystem "laboratory"
csystem "manual"
csystem "trading"
csystem "task"
