local entities = {
    {
        prototype_name = "指挥中心",
        dir = "N",
        x = 126,
        y = 120,
        items = {
            {"物流中心I",1},
            {"车辆厂I",2},
            {"铁制电线杆",20},
            {"物流需求站", 100},
            {"无人机仓库", 100}, 
            {"建造中心",3},
            {"道路建造站",5},
            {"管道建造站",5},
        },
    },
    {
        prototype_name = "组装机残骸",
        dir = "N",
        items = {
            {"采矿机设计图",2},
            {"电线杆设计图",6},
            {"熔炼炉设计图",2},
            {"组装机设计图",2},
            {"空气过滤器设计图",4},
            {"水电站设计图",2},
        },
        x = 111,
        y = 129,
    },
    {
        prototype_name = "抽水泵残骸",
        dir = "S",
        items = {
            {"采矿机设计图",2},
            {"电线杆设计图",6},
            {"无人机仓库设计图",4},
            {"科研中心设计图",1},
            {"道路建造站设计图",2},
            {"管道建造站设计图",2},
            {"送货车站设计图",2},
            {"收货车站设计图",2},
            {"铁板",64},
        },
        x = 120,
        y = 126,
    },
    {
        prototype_name = "无人机仓库",
        dir = "N",
        x = 120,
        y = 130,
    },
    {
        prototype_name = "建造中心",
        dir = "S",
        x = 120,
        y = 134,
    },
    {
        prototype_name = "排水口残骸",
        dir = "S",
        items = {
            {"破损运输车辆",4},
            {"太阳能板设计图",6},
            {"蓄电池设计图",15},
	        {"地下水挖掘机设计图",4},
	        {"电解厂设计图",1},
	        {"化工厂设计图",3},
        },
        x = 133,
        y = 122,
    },
    {
        prototype_name = "组装机I",
        dir = "S",
        x = 133,
        y = 117,
    },
    {
        prototype_name = "熔炼炉I",
        dir = "N",
        x = 140,
        y = 126,
    },
}

local road = {
    {
        prototype_name = "砖石公路-U型-01",
        dir = "N",
        x = 116,
        y = 139,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 138,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 137,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 136,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 135,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 134,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 133,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 132,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 131,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 130,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 129,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 128,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 127,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 116,
        y = 126,
    },
    {
        prototype_name = "砖石公路-L型-01",
        dir = "E",
        x = 116,
        y = 125,
    },
    -- {
    --     prototype_name = "砖石公路-U型-01",
    --     dir = "W",
    --     x = 117,
    --     y = 125,
    -- },
------------------------

    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 117,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 118,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 119,
        y = 125,
    },

    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 120,
        y = 125,
    },
-------------------------
    -- {
    --     prototype_name = "砖石公路-U型-01",
    --     dir = "E",
    --     x = 120,
    --     y = 125,
    -- },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 121,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 122,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 123,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 124,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 125,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 126,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 127,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 128,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 129,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 130,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 131,
        y = 125,
    },

    ----------------
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 132,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 133,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 134,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 135,
        y = 125,
    },
    ------------------
    -- {
    --     prototype_name = "砖石公路-U型-01",
    --     dir = "W",
    --     x = 132,
    --     y = 125,
    -- },
    -- {
    --     prototype_name = "砖石公路-U型-01",
    --     dir = "E",
    --     x = 135,
    --     y = 125,
    -- },

    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 136,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 137,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 138,
        y = 125,
    },
    {
        prototype_name = "砖石公路-T型-01",
        dir = "S",
        x = 139,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 140,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 141,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 142,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 143,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 144,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 145,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 146,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 147,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "E",
        x = 148,
        y = 125,
    },
    -------------------------------
    

    
    {
        prototype_name = "砖石公路-U型-01",
        dir = "W",
        x = 149,
        y = 125,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 124,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 123,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 122,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 121,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 120,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 119,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 118,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 117,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 116,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 115,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 114,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 113,
    },
    {
        prototype_name = "砖石公路-I型-01",
        dir = "N",
        x = 139,
        y = 112,
    },
    {
        prototype_name = "砖石公路-U型-01",
        dir = "S",
        x = 139,
        y = 111,
    },
}

return {
    entities = entities,
    road = road,
}