require "init.type"
require "init.component"
require "init.system"

local pipeline = require "register.pipeline"
pipeline "update"
    .stage "update"
pipeline "build"
    .stage "init"
    .stage "build"
pipeline "backup"
    .stage "backup"
pipeline "restore"
    .stage "restore"
